import { useState } from "react";
import { publicRouteSlugs, routeCatalog } from "../../../src/routes.js";
import { LineBreakText, useLanguage } from "../i18n";
import { BookingForm } from "./BookingForm";
import { Header } from "./Header";

type Vehicle = "vito" | "sprinter";

const serviceItems = [
  ["trackingTitle", "Flight tracking", "trackingBody", "We monitor your flight in real time and adjust your pick-up automatically, at no extra charge."],
  ["chauffeurTitle", "Professional chauffeurs", "chauffeurBody", "Immaculately presented, discreet and selected for their local knowledge and service standards."],
  ["greetTitle", "Meet & greet", "greetBody", "Your chauffeur welcomes you in arrivals with a personalised name sign and assists with luggage."],
  ["supportTitle", "24/7 concierge", "supportBody", "A real person is always available by phone or WhatsApp before, during and after your journey."],
  ["priceTitle", "Fixed prices", "priceBody", "The price confirmed is the price you pay. Waiting time, parking and flight delays are included."],
  ["familyTitle", "Family ready", "familyBody", "Age-appropriate child seats, spacious cabins and patient assistance for a relaxed family arrival."],
] as const;

const reviews = [
  ["reviewOne", "A flawless welcome after a late flight. The vehicle was immaculate and our driver was waiting exactly where promised.", "Sophie M.", "United Kingdom"],
  ["reviewTwo", "Professional, calm and completely reliable. Travelling with children felt effortless from the first message.", "Daniel K.", "Germany"],
  ["reviewThree", "The fixed price and immediate WhatsApp support made the whole transfer simple. We will book again.", "Elena P.", "Netherlands"],
] as const;

export function HomePage({ initialLanguage }: { initialLanguage: string }) {
  const { language, t } = useLanguage();
  const [fleet, setFleet] = useState<Vehicle>("sprinter");
  const [selection, setSelection] = useState<{ route: string; vehicle: Vehicle; nonce: number }>();
  const [openFaq, setOpenFaq] = useState(0);
  const routePrefix = ["de", "tr", "ru"].includes(initialLanguage) ? `/${initialLanguage}` : "";
  const privacyHref = initialLanguage === "de" ? "/de/datenschutz/" : initialLanguage === "tr" ? "/tr/gizlilik/" : initialLanguage === "ru" ? "/ru/privacy/" : "/privacy/";
  const imprintHref = initialLanguage === "de" ? "/de/impressum/" : initialLanguage === "tr" ? "/tr/kunye/" : initialLanguage === "ru" ? "/ru/impressum/" : "/impressum.html";
  const fleetCopy = fleet === "sprinter"
    ? { name: "Mercedes Sprinter", classKey: "fleetVclassClass", classFallback: "Business · First Class", descriptionKey: "fleetVclassDescription", descriptionFallback: "Spacious VIP transport for larger groups, with generous room for passengers and luggage.", guests: 13, bags: 12 }
    : { name: "Mercedes Vito", classKey: "fleetVitoClass", classFallback: "VIP · Grand Touring", descriptionKey: "fleetVitoDescription", descriptionFallback: "A refined private cabin for couples, families and smaller groups.", guests: 7, bags: 6 };

  const bookRoute = (route: string, vehicle: Vehicle = "vito") => {
    setSelection({ route, vehicle, nonce: Date.now() });
  };

  const faqItems = Array.from({ length: 5 }, (_, index) => {
    const number = ["One", "Two", "Three", "Four", "Five"][index];
    return [t(`faq${number}Q`, "Frequently asked question"), t(`faq${number}A`, "Contact us for complete details.")];
  });

  return (
    <>
      <Header />
      <main>
        <section className="hero" id="top">
          <picture className="hero-media"><source srcSet="/assets/optimized/antalya-coastline-hero.webp" type="image/webp" /><img src="/assets/optimized/antalya-coastline-hero.jpg" alt="Luxury black executive van driving along Antalya's coastline" width="1672" height="941" fetchPriority="high" /></picture>
          <div className="hero-shade" /><div className="hero-grain" />
          <div className="hero-content"><div className="hero-copy"><div className="eyebrow light"><span /><p>{t("heroEyebrow", "Private chauffeur service · Antalya")}</p></div><div className="campaign-badge"><span>{t("campaignBadge", "Online special")}</span><strong>{t("campaignDiscount", "25% off")}</strong><span>{t("campaignScope", "all transfer prices")}</span></div><h1><LineBreakText value={t("heroTitle", "Premium Airport<br />Transfers in Antalya")} /></h1><p className="hero-subtitle">{t("heroSubtitle", "Private chauffeur-driven transfers from Antalya Airport to Belek, Side, Kemer and Alanya.")}</p><div className="hero-buttons"><a className="button button-gold" href="#booking"><span>{t("bookTransfer", "Book your transfer")}</span><span aria-hidden="true">→</span></a><a className="button button-glass" href="#booking">{t("instantQuote", "Get instant quote")}</a></div></div><div className="hero-proof"><div className="rating-lockup"><div className="stars" aria-label="5 out of 5 stars">★★★★★</div><strong>4.9</strong></div><div className="proof-divider" /><p><span>{t("googleRated", "Google rated")}</span><strong>{t("trustedGuests", "Trusted by 2,500+ guests")}</strong></p></div></div>
          <div className="hero-scroll" aria-hidden="true"><span>{t("discover", "Discover")}</span><i /></div>
        </section>
        <div className="trust-bar" aria-label="Service credentials">{[["tbLicensed", "TÜRSAB Licensed"], ["tbFlightTracking", "Flight Tracking"], ["tbFixedPrice", "Fixed Pricing"], ["tb247Concierge", "24/7 Concierge"], ["tbChildSeats", "Child Seats Included"]].map(([key, fallback]) => <div className="trust-bar-item" key={key}><span className="trust-bar-check">✓</span><span>{t(key, fallback)}</span></div>)}</div>

        <BookingForm selection={selection} />

        <section className="trust-strip" aria-label="Service guarantees">{[["flightTracking", "Real-time flight tracking", "◷"], ["fixedPrice", "Fixed price guarantee", "◇"], ["meetGreet", "Personal meet & greet", "✦"], ["speakingDrivers", "English & German speaking", "◎"]].map(([key, fallback, icon]) => <div key={key}><span className="react-icon">{icon}</span><span>{t(key, fallback)}</span></div>)}</section>
        <div className="price-strip"><span className="price-strip-label">{t("fromAirport", "From Antalya Airport")}</span><div className="price-strip-pills">{(["belek", "side", "kemer", "alanya", "antalya"] as const).map((slug) => <button className="price-pill" type="button" key={slug} onClick={() => bookRoute(slug)}>{routeCatalog[slug].names[language as keyof typeof routeCatalog[typeof slug]["names"]] ?? routeCatalog[slug].names.en} <span className="was-price">€{routeCatalog[slug].originalPrices.vito}</span><strong>€{routeCatalog[slug].prices.vito}</strong></button>)}</div><span className="price-strip-note">{t("campaignApplied", "Online discount already applied")}</span></div>

        <section className="editorial-intro section"><div className="section-index">01</div><div className="eyebrow"><span /><p>{t("welcomeEyebrow", "Welcome to a better arrival")}</p></div><div className="editorial-grid"><h2><LineBreakText value={t("welcomeTitle", "Travel beautifully.<br />Arrive effortlessly.")} /></h2><div><p>{t("welcomeBody", "From the moment your flight lands, every detail is considered. Your chauffeur waits inside arrivals, handles your luggage and guides you to a meticulously prepared private vehicle.")}</p><a className="text-link" href="#services"><span>{t("ourStandards", "Our service standards")}</span><span>→</span></a></div></div><div className="luxury-stats"><div><strong>24/7</strong><span>{t("concierge", "Concierge support")}</span></div><div><strong>2,500+</strong><span>{t("guestsWelcomed", "Guests welcomed")}</span></div><div><strong>4.9/5</strong><span>{t("guestRating", "Average guest rating")}</span></div><div><strong>100%</strong><span>{t("privateTransfers", "Private transfers")}</span></div></div></section>

        <section className="fleet section-dark" id="fleet"><div className="section section-inner"><div className="section-heading light-heading"><div><div className="eyebrow light"><span /><p>{t("fleetEyebrow", "The fleet")}</p></div><h2><LineBreakText value={t("fleetTitle", "Your private space,<br />refined in every detail.")} /></h2></div><p>{t("fleetIntro", "Travel in quiet comfort with generous space for your family, golf equipment and luggage.")}</p></div><div className="fleet-showcase"><div className="fleet-image"><img src="/assets/optimized/chauffeur-arrival.jpg" alt="Professional chauffeur opening a luxury executive van" width="1600" height="765" loading="lazy" /><div className="image-badge"><span>{t("signatureFleet", "Signature fleet")}</span><strong>{fleetCopy.name.replace("Mercedes ", "")}</strong></div></div><div className="fleet-panel"><div className="fleet-tabs" role="tablist"><button className={`fleet-tab${fleet === "sprinter" ? " active" : ""}`} type="button" onClick={() => setFleet("sprinter")}>Mercedes Sprinter</button><button className={`fleet-tab${fleet === "vito" ? " active" : ""}`} type="button" onClick={() => setFleet("vito")}>Mercedes Vito</button></div><div className="fleet-panel-copy"><span className="mini-label">{t(fleetCopy.classKey, fleetCopy.classFallback)}</span><h3>{fleetCopy.name}</h3><p>{t(fleetCopy.descriptionKey, fleetCopy.descriptionFallback)}</p></div><div className="fleet-capacity"><div><span className="react-icon">♙</span><span><strong>{fleetCopy.guests}</strong> {t("passengers", "passengers")}</span></div><div><span className="react-icon">▣</span><span><strong>{fleetCopy.bags}</strong> {t("suitcases", "suitcases")}</span></div></div><ul className="amenity-list">{[["television", "In-vehicle television"], ["coldDrinks", "Cold drinks"], ["snacks", "Snacks"], ["childSeats", "Child seat available"], ["wifi", "Complimentary WiFi"]].map(([key, fallback]) => <li key={key}><span>✓</span><span>{t(key, fallback)}</span></li>)}</ul><div className="fleet-welcome-note"><span>✓</span><span>{t("nameSignGreeting", "Meet & greet with a personalised name sign")}</span></div><button className="button button-outline-gold" type="button" onClick={() => document.querySelector("#booking")?.scrollIntoView({ behavior: "smooth" })}>{t("reserveVehicle", "Reserve this vehicle")} →</button></div></div><div className="interior-banner"><img src="/assets/optimized/executive-interior.jpg" alt="Cream leather executive seating inside a luxury passenger van" width="1400" height="933" loading="lazy" /><div className="interior-copy"><span className="mini-label">{t("insideVclass", "Inside the Sprinter")}</span><h3><LineBreakText value={t("interiorTitle", "A private lounge between<br />the airport and your hotel.")} /></h3></div></div></div></section>

        <section className="service section" id="services"><div className="section-heading"><div><div className="eyebrow"><span /><p>{t("serviceEyebrow", "The Antalya VIP standard")}</p></div><h2><LineBreakText value={t("serviceTitle", "More than a transfer.<br />A considered welcome.")} /></h2></div><p>{t("serviceIntro", "Hotel-level attention, experienced local chauffeurs and complete peace of mind from runway to resort.")}</p></div><div className="service-grid">{serviceItems.map(([titleKey, title, bodyKey, body], index) => <article className={`service-card${index === 0 ? " featured" : ""}`} key={titleKey}><span className="service-number">{String(index + 1).padStart(2, "0")}</span><div className="service-icon" aria-hidden="true">{["✈", "♙", "✦", "◉", "€", "♧"][index]}</div><h3>{t(titleKey, title)}</h3><p>{t(bodyKey, body)}</p></article>)}</div></section>

        <section className="routes section" id="routes"><div className="section-heading route-heading"><div><div className="eyebrow"><span /><p>{t("routesEyebrow", "Our most requested journeys")}</p></div><h2><LineBreakText value={t("routesTitle", "From Antalya Airport<br />to the Turkish Riviera.")} /></h2></div><p>{t("routesIntro", "All prices are per vehicle, never per passenger, with complimentary waiting time included.")}</p></div><div className="route-grid-react">{publicRouteSlugs.map((slug) => { const route = routeCatalog[slug]; const routeName = route.names[language as keyof typeof route.names] ?? route.names.en; return <article className="route-card" key={slug}><div className="route-card-top"><span>AYT</span><span>→</span><strong>{routeName}</strong></div><div className="route-card-details"><span>{route.distanceKm} km</span><span>{route.duration[language as keyof typeof route.duration] ?? route.duration.en}</span></div><div className="route-card-prices"><span><small>Vito</small><s>€{route.originalPrices.vito}</s><strong>€{route.prices.vito}</strong></span><span><small>Sprinter</small><s>€{route.originalPrices.sprinter}</s><strong>€{route.prices.sprinter}</strong></span></div><div className="route-card-actions"><button className="button button-gold route-price-button" type="button" onClick={() => bookRoute(slug)}>{t("bookNow", "Book now")}</button><a className="text-link" href={`${routePrefix}/transfers/${slug}/`}>{t("discover", "Discover")} →</a></div></article>; })}</div></section>

        <section className="reviews section-dark" id="reviews"><div className="section section-inner"><div className="section-heading light-heading"><div><div className="eyebrow light"><span /><p>{t("reviewsEyebrow", "Guest stories")}</p></div><h2><LineBreakText value={t("reviewsTitle", "Service remembered<br />long after arrival.")} /></h2></div><div className="google-rating"><span className="stars">★★★★★</span><strong>4.9</strong><small>{t("googleReviews", "Google reviews")}</small></div></div><div className="review-grid-react">{reviews.map(([key, fallback, name, country]) => <blockquote className="review-card" key={key}><div className="stars">★★★★★</div><p>“{t(key, fallback)}”</p><footer><strong>{name}</strong><span>{country}</span></footer></blockquote>)}</div></div></section>

        <section className="process section"><div className="section-heading"><div><div className="eyebrow"><span /><p>{t("processEyebrow", "Simple by design")}</p></div><h2><LineBreakText value={t("processTitle", "Four steps to a<br />calm arrival.")} /></h2></div></div><div className="process-grid-react">{[["stepOne", "Book online", "stepOneBody", "Choose your route and send your details."], ["stepTwo", "We confirm", "stepTwoBody", "You receive confirmation by WhatsApp or email."], ["stepThree", "We track", "stepThreeBody", "Your flight is monitored in real time."], ["stepFour", "You arrive", "stepFourBody", "Meet your chauffeur and travel privately."]].map(([titleKey, title, bodyKey, body], index) => <article key={titleKey}><span>{String(index + 1).padStart(2, "0")}</span><h3>{t(titleKey, title)}</h3><p>{t(bodyKey, body)}</p></article>)}</div></section>

        <section className="pricing-transparency section" id="pricing"><div className="section-heading"><div><div className="eyebrow"><span /><p>{t("pricingEyebrow", "Transparent by nature")}</p></div><h2><LineBreakText value={t("pricingTitle", "Customer-first pricing.<br />You pay what is fair.")} /></h2></div><p>{t("pricingIntro", "Your fixed online price includes the complete private journey.")}</p></div><div className="pricing-grid-react">{[["pricingFixedPrice", "Fixed price", "fixedPriceExample", "Confirmed before travel", "fixedPriceDesc", "Parking, waiting and flight delays included."], ["distancePrice", "Clear route", "distancePriceExample", "One vehicle, one total", "distancePriceDesc", "No per-passenger charge or hidden supplement."], ["youPay", "You pay", "youPayPrice", "The confirmed total", "youPayDesc", "Pay directly in the vehicle after the service."]].map(([titleKey, title, valueKey, value, bodyKey, body]) => <article className="pricing-card" key={titleKey}><span className="mini-label">{t(titleKey, title)}</span><strong>{t(valueKey, value)}</strong><p>{t(bodyKey, body)}</p></article>)}</div><p className="pricing-note">{t("pricingNote", "All prices are shown in EUR per vehicle.")}</p></section>

        <section className="faq section" id="faq"><div className="faq-layout"><div><div className="eyebrow"><span /><p>{t("faqEyebrow", "Good to know")}</p></div><h2>{t("faqTitle", "Before you travel.")}</h2><p>{t("faqIntro", "Everything you need for a smooth private transfer.")}</p><a className="button button-outline" href="https://wa.me/905302655790" target="_blank" rel="noreferrer">{t("askQuestion", "Ask us a question")}</a></div><div className="faq-list">{faqItems.map(([question, answer], index) => <article className={`faq-item${openFaq === index ? " open" : ""}`} key={question}><button type="button" aria-expanded={openFaq === index} onClick={() => setOpenFaq(openFaq === index ? -1 : index)}><span>{question}</span><span>{openFaq === index ? "−" : "+"}</span></button>{openFaq === index && <p>{answer}</p>}</article>)}</div></div></section>

        <section className="contact section-dark" id="contact"><div className="section section-inner contact-grid"><div><div className="eyebrow light"><span /><p>{t("contactEyebrow", "Your journey starts here")}</p></div><h2><LineBreakText value={t("contactTitle", "Arrive in Antalya<br />exceptionally well.")} /></h2><p>{t("contactBody", "Our concierge is ready 24 hours a day for reservations and questions.")}</p></div><div className="contact-actions"><a className="button button-gold" href="https://wa.me/905302655790" target="_blank" rel="noreferrer">{t("whatsappUs", "WhatsApp us")} ↗</a><a href="tel:+905302655790"><small>{t("callUs", "Call us")}</small><strong>+90 530 265 57 90</strong></a><a href="mailto:support@antalyaviptourism.com"><small>{t("emailUs", "Email us")}</small><strong>support@antalyaviptourism.com</strong></a></div></div></section>
      </main>
      <footer className="site-footer"><div className="footer-main"><div className="footer-brand"><img src="/assets/optimized/logo.png" alt="Antalya VIP Tourism" width="160" height="120" /><p>{t("footerTagline", "Private airport transfers, thoughtfully delivered.")}</p></div><div><strong>{t("explore", "Explore")}</strong><a href="#fleet">{t("navFleet", "Fleet")}</a><a href="#services">{t("navService", "Service")}</a><a href="#routes">{t("navRoutes", "Routes")}</a></div><div><strong>{t("information", "Information")}</strong><a href={privacyHref}>Privacy</a><a href={imprintHref}>Imprint</a><button type="button" data-open-consent>Privacy settings</button></div></div><div className="footer-bottom"><span>© 2026 Antalya VIP Tourism</span><span>{t("licensed", "Licensed private transfer operator · TÜRSAB compliant")}</span></div></footer>
      <a className="floating-whatsapp" href="https://wa.me/905302655790" target="_blank" rel="noreferrer" aria-label="Chat on WhatsApp"><span>◉</span><span>{t("chatWithUs", "Chat with us")}</span></a>
      <div className="mobile-book-bar"><a className="button button-gold" href="#booking">{t("bookTransfer", "Book your transfer")}</a></div>
    </>
  );
}
