import { localizedRoute, publicRouteSlugs, routeCatalog } from "../../../src/routes.js";
import type { IndexableLanguage } from "../lib/seo";
import { routeCopy } from "../lib/seo";
import { BookingForm } from "./BookingForm";
import { StaticPageHeader } from "./StaticPageHeader";

type LocalizedRoute = NonNullable<ReturnType<typeof localizedRoute>>;

const copy = {
  en: {
    home: "Home", routes: "Transfer routes", priceHeading: "Fixed transfer prices", included: "Included in the price", duration: "Estimated time", distance: "Distance", from: "Price from", book: "Book your transfer", faq: "Frequently asked questions", other: "Other Antalya Airport transfers", campaign: "Online special: 25% discount already applied to all transfer prices.", contact: "Contact us on WhatsApp for bookings and questions.", privacy: "Privacy", imprint: "Imprint", privacyUrl: "/privacy/", imprintUrl: "/impressum.html", vito: "Mercedes Vito · up to 7 passengers", sprinter: "Mercedes Sprinter · up to 13 passengers", intro: (name: string, duration: string, distance: string) => `The ${distance} journey from Antalya Airport to ${name} takes approximately ${duration} in normal traffic. Your chauffeur meets you in arrivals with a name sign and drives directly to your accommodation.`, items: ["Personal meet and greet", "Real-time flight tracking", "Airport parking and waiting", "Luggage assistance and bottled water", "Free child seat on request"], faqItems: (name: string, price: number, duration: string) => [[`How long is the transfer from Antalya Airport to ${name}?`, `The journey takes approximately ${duration} in normal traffic.`], [`What is the fixed transfer price to ${name}?`, `Mercedes Vito prices start from €${price} per vehicle. The confirmed total is shown when booking.`], ["What happens if my flight is delayed?", "We track your flight in real time and adjust the meeting time at no extra charge."]],
  },
  de: {
    home: "Startseite", routes: "Transferrouten", priceHeading: "Feste Transferpreise", included: "Im Preis enthalten", duration: "Geschätzte Fahrzeit", distance: "Entfernung", from: "Preis ab", book: "Transfer buchen", faq: "Häufig gestellte Fragen", other: "Weitere Transfers vom Flughafen Antalya", campaign: "Online Spezial: 25% Rabatt ist in allen Transferpreisen bereits abgezogen.", contact: "Für Buchungen und Fragen erreichen Sie uns über WhatsApp.", privacy: "Datenschutz", imprint: "Impressum", privacyUrl: "/de/datenschutz/", imprintUrl: "/de/impressum/", vito: "Mercedes Vito · bis 7 Personen", sprinter: "Mercedes Sprinter · bis 13 Personen", intro: (name: string, duration: string, distance: string) => `Die ${distance} lange Fahrt vom Flughafen Antalya nach ${name} dauert bei normalem Verkehr ungefähr ${duration}. Ihr Chauffeur empfängt Sie in der Ankunftshalle mit Namensschild und fährt direkt zu Ihrer Unterkunft.`, items: ["Persönlicher Empfang mit Namensschild", "Flugverfolgung in Echtzeit", "Flughafenparken und Wartezeit", "Gepäckhilfe und Mineralwasser", "Kostenloser Kindersitz auf Wunsch"], faqItems: (name: string, price: number, duration: string) => [[`Wie lange dauert der Transfer vom Flughafen Antalya nach ${name}?`, `Die Fahrt dauert bei normalem Verkehr ungefähr ${duration}.`], [`Was kostet der Festpreis-Transfer nach ${name}?`, `Die Preise für einen Mercedes Vito beginnen bei €${price} pro Fahrzeug. Der bestätigte Gesamtpreis wird bei der Buchung angezeigt.`], ["Was passiert bei einer Flugverspätung?", "Wir verfolgen Ihren Flug in Echtzeit und passen die Abholzeit ohne Aufpreis an."]],
  },
  tr: {
    home: "Ana sayfa", routes: "Transfer rotaları", priceHeading: "Sabit transfer fiyatları", included: "Fiyata dahil olanlar", duration: "Tahmini süre", distance: "Mesafe", from: "Başlangıç fiyatı", book: "Transferinizi ayırtın", faq: "Sık sorulan sorular", other: "Diğer Antalya Havalimanı transferleri", campaign: "Online'a özel: Tüm transfer fiyatlarına %25 indirim uygulanmıştır.", contact: "Rezervasyon ve sorularınız için WhatsApp üzerinden bize ulaşın.", privacy: "Gizlilik", imprint: "Künye", privacyUrl: "/tr/gizlilik/", imprintUrl: "/tr/kunye/", vito: "Mercedes Vito · 7 yolcuya kadar", sprinter: "Mercedes Sprinter · 13 yolcuya kadar", intro: (name: string, duration: string, distance: string) => `Antalya Havalimanı ile ${name} arasındaki ${distance} mesafeli yolculuk normal trafik koşullarında yaklaşık ${duration} sürer. Şoförünüz sizi gelen yolcu salonunda isim tabelasıyla karşılar ve doğrudan konaklama adresinize götürür.`, items: ["Kişisel isim tabelasıyla karşılama", "Gerçek zamanlı uçuş takibi", "Havalimanı otoparkı ve bekleme", "Bagaj yardımı ve şişe su", "Talep üzerine ücretsiz çocuk koltuğu"], faqItems: (name: string, price: number, duration: string) => [[`Antalya Havalimanı ile ${name} arası transfer ne kadar sürer?`, `Normal trafik koşullarında yolculuk yaklaşık ${duration} sürer. Trafik ve otel konumu süreyi etkileyebilir.`], [`${name} transferinin sabit fiyatı nedir?`, `Mercedes Vito fiyatları araç başına €${price}'dan başlar. Kesin toplam rezervasyon sırasında gösterilir.`], ["Uçuşum gecikirse ne olur?", "Uçuşunuzu gerçek zamanlı takip eder, karşılama saatini ücretsiz olarak güncelleriz."]],
  },
  ru: {
    home: "Главная", routes: "Маршруты трансфера", priceHeading: "Фиксированные цены", included: "В стоимость включено", duration: "Время в пути", distance: "Расстояние", from: "Цена от", book: "Забронировать трансфер", faq: "Частые вопросы", other: "Другие трансферы из аэропорта Антальи", campaign: "Онлайн-акция: скидка 25% уже применена ко всем трансферам.", contact: "Для бронирования и вопросов напишите нам в WhatsApp.", privacy: "Конфиденциальность", imprint: "Правовая информация", privacyUrl: "/ru/privacy/", imprintUrl: "/ru/impressum/", vito: "Mercedes Vito · до 7 пассажиров", sprinter: "Mercedes Sprinter · до 13 пассажиров", intro: (name: string, duration: string, distance: string) => `Поездка из аэропорта Антальи в ${name} на расстояние ${distance} занимает примерно ${duration} при обычном движении. Водитель встретит вас в зале прилёта с именной табличкой и отвезёт прямо к месту проживания.`, items: ["Встреча с именной табличкой", "Отслеживание рейса в реальном времени", "Парковка и ожидание в аэропорту", "Помощь с багажом и вода", "Бесплатное детское кресло по запросу"], faqItems: (name: string, price: number, duration: string) => [[`Сколько длится трансфер из аэропорта Антальи в ${name}?`, `При обычном движении поездка занимает около ${duration}. Точное время зависит от дорожной ситуации и расположения отеля.`], [`Сколько стоит трансфер в ${name}?`, `Стоимость Mercedes Vito начинается от €${price} за автомобиль. Итоговая фиксированная цена показывается при бронировании.`], ["Что произойдёт при задержке рейса?", "Мы отслеживаем рейс в реальном времени и бесплатно корректируем время встречи."]],
  },
} as const;

export function TransferPage({ language, route }: { language: IndexableLanguage; route: LocalizedRoute }) {
  const text = copy[language];
  const seo = routeCopy(language);
  const prefix = language === "en" ? "" : `/${language}`;
  const homeHref = `${prefix}/`;
  const heading = seo.heading(route.name);
  const faq = text.faqItems(route.name, route.prices.vito, route.durationLabel);

  return (
    <>
      <StaticPageHeader homeHref={homeHref} homeLabel={text.home} secondaryHref="#details" secondaryLabel={text.routes} tertiaryHref="#contact" tertiaryLabel="WhatsApp" ctaHref={`${homeHref}#booking`} ctaLabel={text.book} />
      <main>
        <section className="localized-route"><div className="eyebrow light"><span /><p>Antalya VIP Tourism</p></div><h1>{heading}</h1><p>{seo.description(route.name, route.prices.vito)}</p><p className="localized-campaign">{text.campaign}</p><div className="localized-stats"><div><strong>{route.durationLabel}</strong><span>{text.duration}</span></div><div><strong>{route.distance}</strong><span>{text.distance}</span></div><div><strong>€{route.prices.vito}</strong><span>{text.from}</span></div></div></section>
        <section className="localized-content" id="details"><div className="localized-grid"><div><h2>{heading}</h2><p>{text.intro(route.name, route.durationLabel, route.distance)}</p><h3>{text.included}</h3><ul>{text.items.map((item) => <li key={item}>{item}</li>)}</ul></div><aside><h2>{text.priceHeading}</h2><div className="localized-price"><p>{text.vito}</p><strong>€{route.prices.vito}</strong></div><div className="localized-price"><p>{text.sprinter}</p><strong>€{route.prices.sprinter}</strong></div><p><a className="button button-gold" href={`${homeHref}#booking`}>{text.book}</a></p></aside></div></section>
        <section className="localized-faq"><h2>{text.faq}</h2>{faq.map(([question, answer]) => <article key={question}><h3>{question}</h3><p>{answer}</p></article>)}</section>
        <section className="localized-links"><h2>{text.other}</h2><div>{publicRouteSlugs.filter((slug) => slug !== route.slug).map((slug) => <a href={`${prefix}/transfers/${slug}/`} key={slug}>{routeCatalog[slug].names[language]}</a>)}</div></section>
        <section className="localized-contact" id="contact"><h2>{text.book}</h2><p>{text.contact}</p><a className="button button-gold" href="https://wa.me/905302655790">WhatsApp</a></section>
      </main>
      <div hidden aria-hidden="true"><BookingForm selection={{ route: route.slug, vehicle: "vito", nonce: 1 }} scrollOnSelect={false} /></div>
      <footer><div className="footer-bottom"><span>© 2026 Antalya VIP Tourism</span><span><a href={text.imprintUrl}>{text.imprint}</a> · <a href={text.privacyUrl}>{text.privacy}</a></span></div></footer>
    </>
  );
}
