import { localizedRoute, publicRouteSlugs, routeCatalog } from "../../../src/routes.js";
import { hotelsForRegion } from "../../../src/hotels.js";
import type { IndexableLanguage } from "../lib/seo";
import { routeCopy } from "../lib/seo";
import { BookingForm } from "./BookingForm";
import { StaticPageHeader } from "./StaticPageHeader";

type LocalizedRoute = NonNullable<ReturnType<typeof localizedRoute>>;

const germanLandingHotels: Partial<Record<string, readonly string[]>> = {
  belek: ["Rixos Premium Belek", "The Land of Legends", "Maxx Royal Belek", "Regnum Carya", "Gloria Golf Resort", "Cornelia Diamond Golf Resort & Spa", "IC Hotels Santai Family Resort"],
  side: ["Arum Barut Collection", "Side Star Resort", "Royal Dragon Hotel", "Barut Hemera", "Voyage Sorgun", "Sentido Flora Garden", "Crystal Sunset Luxury Resort & Spa"],
  kemer: ["Rixos Premium Kemer", "Maxx Royal Kemer Resort", "Orange County Resort Hotel Kemer", "Paloma Pasha Resort", "Club Hotel Phaselis Rose"],
  alanya: ["Utopia World Hotel", "Sentido Gold Island Hotel", "Q Premium Resort Hotel Alanya", "Kirman Arycanda De Luxe", "Delphin Diva Premiere"],
  kizilagac: ["Starlight Resort Hotel", "Sunrise Resort Hotel", "Crystal Admiral Resort", "Club Hotel Turan Prince", "Selectum Family Resort"],
  tekirova: ["Rixos Premium Tekirova", "Amara Prestige Hotel", "Nirvana Dolce Vita", "Club Marco Polo", "Pirate’s Beach Club"],
};

const germanRegionCopy: Partial<Record<string, { about: string; routeDetails: string }>> = {
  belek: { about: "Belek liegt östlich von Antalya und ist besonders für Golfplätze, große All-inclusive-Resorts und breite Sandstrände bekannt. Die Hotelanlagen verteilen sich zwischen Kadriye und der Küste bei Serik; deshalb ist die genaue Hoteladresse bei der Reservierung hilfreich.", routeDetails: "Die Fahrt führt vom Flughafen Antalya über die D400 in Richtung Serik und Belek. Für Familien, Golfer und Gäste mit spätem Flug ist der direkte Privattransfer praktisch, weil Sie ohne Sammelstopps oder Umstieg direkt an Ihrer Unterkunft ankommen." },
  side: { about: "Side verbindet eine historische Altstadt mit langen Sandstränden und weitläufigen Ferienanlagen. Zum Urlaubsort gehören neben Side auch die beliebten Hotelzonen Kumköy, Evrenseki, Çolaklı, Sorgun und Titreyengöl.", routeDetails: "Vom Flughafen Antalya führt die Strecke über die Küstenstraße in Richtung Manavgat und Side. Besonders bei einer späten Ankunft ist ein privates Fahrzeug angenehm: Ihre Reisegruppe fährt direkt zum gebuchten Resort, ohne auf andere Hotelgäste zu warten." },
  kemer: { about: "Kemer liegt westlich von Antalya zwischen dem Taurusgebirge und dem Mittelmeer. Die Region umfasst Kemer Zentrum sowie Beldibi, Göynük, Kiriş und Çamyuva – Orte mit Strandhotels, Jachthafen und Bergkulisse.", routeDetails: "Die direkte Fahrt folgt der Küste westlich von Antalya. Ihr Fahrer bringt Sie ohne Umstieg zu Ihrem Hotel; das ist besonders bequem, wenn Sie mit Kindern, Sportgepäck oder nach einer Abendlandung anreisen." },
  alanya: { about: "Alanya ist eines der beliebtesten Ferienziele an der türkischen Riviera und liegt deutlich weiter östlich als die Resorts um Antalya. Neben dem Zentrum gehören Mahmutlar, Kestel, Avsallar, Türkler und Okurcalar zu den häufig angefragten Hotelgebieten.", routeDetails: "Die längere Küstenfahrt macht einen festen Fahrzeugpreis besonders transparent. Mit einem Privattransfer reisen Sie direkt mit Ihrer eigenen Gruppe und können nach der Landung entspannt bis vor die Rezeption Ihres Hotels weiterfahren." },
  kizilagac: { about: "Kızılağaç liegt östlich von Manavgat und ist für weitläufige Strandresorts und ruhige Familienferien bekannt. Die Gegend grenzt an Sorgun und Manavgat; viele Hotels liegen etwas abseits der Hauptstraße direkt am Meer.", routeDetails: "Vom Flughafen Antalya fahren Sie über die D400 in Richtung Manavgat und anschließend weiter nach Kızılağaç. Ein privates Fahrzeug erspart die zusätzlichen Hotelstopps, die bei Sammeltransfers gerade auf dieser Strecke üblich sein können." },
  tekirova: { about: "Tekirova liegt südlich von Kemer am Rand des Olympos-Beydağları-Nationalparks. Der Ort verbindet gepflegte Resortanlagen mit kleinen Buchten und liegt nahe der antiken Stätte Phaselis.", routeDetails: "Die Fahrt führt vom Flughafen Antalya über Kemer weiter nach Tekirova. Die Küstenlage und die Entfernung machen einen direkten Transfer sinnvoll: Sie fahren ohne Umstieg und ohne Wartezeit auf andere Gäste bis zu Ihrem Hotel." },
};

const copy = {
  zh: { home: "首页", routes: "接送路线", priceHeading: "固定接送价格", included: "价格包含", duration: "预计时间", distance: "距离", from: "价格起于", book: "预订您的接送", faq: "常见问题", other: "其他安塔利亚机场接送", campaign: "所有接送路线均提供在线特惠价格。", contact: "预订及咨询请通过WhatsApp联系我们。", privacy: "隐私政策", imprint: "版本说明", privacyUrl: "/privacy/", imprintUrl: "/impressum.html", vito: "Mercedes Vito · 最多6位乘客", sprinter: "Mercedes Sprinter · 最多12位乘客", intro: (name: string, duration: string, distance: string) => `从安塔利亚机场到${name}的${distance}行程，在正常交通情况下约需${duration}。您的司机将在到达大厅迎接您，并直接送您前往住宿地。`, items: ["专人接机问候", "实时航班追踪", "机场停车与等候", "行李协助及瓶装水", "可应要求免费提供儿童座椅"], faqItems: (name: string, price: number, duration: string) => [[`从安塔利亚机场到${name}的接送需要多长时间？`, `在正常交通情况下，行程约需${duration}。`], [`到${name}的固定接送价格是多少？`, `Mercedes Vito价格每车€${price}起。确认的总价将在预订时显示。`], ["如果我的航班延误怎么办？", "我们会实时追踪您的航班，并免费调整接机时间。"], ["我的司机会在机场等候多久？", "落地后的前90分钟免费包含在内，如果您的航班延误，等候时间会自动顺延。"], ["我该如何支付接送费用？", "在行程开始时以现金支付给您的司机——即您预订时的固定价格，按每车计算。"]],
  },
  da: { home: "Hjem", routes: "Transferruter", priceHeading: "Faste transferpriser", included: "Inkluderet i prisen", duration: "Anslået tid", distance: "Afstand", from: "Pris fra", book: "Bestil din transfer", faq: "Ofte stillede spørgsmål", other: "Andre transfers fra Antalya Lufthavn", campaign: "Særlige online-priser er tilgængelige for alle transferruter.", contact: "Kontakt os på WhatsApp for bestillinger og spørgsmål.", privacy: "Privatliv", imprint: "Impressum", privacyUrl: "/privacy/", imprintUrl: "/impressum.html", vito: "Mercedes Vito · op til 6 passagerer", sprinter: "Mercedes Sprinter · op til 12 passagerer", intro: (name: string, duration: string, distance: string) => `Rejsen på ${distance} fra Antalya Lufthavn til ${name} tager cirka ${duration} i normal trafik. Din chauffør møder dig i ankomsthallen og kører direkte til din overnatning.`, items: ["Personlig Meet & Greet", "Flysporing i realtid", "Parkering og ventetid i lufthavnen", "Bagagehjælp og vand på flaske", "Gratis barnesæde efter ønske"], faqItems: (name: string, price: number, duration: string) => [[`Hvor lang er transferen fra Antalya Lufthavn til ${name}?`, `Rejsen tager cirka ${duration} i normal trafik.`], [`Hvad er den faste transferpris til ${name}?`, `Priser for Mercedes Vito starter fra €${price} pr. køretøj. Den bekræftede totalpris vises ved bestilling.`], ["Hvad sker der, hvis mit fly er forsinket?", "Vi sporer dit fly i realtid og justerer mødetidspunktet uden ekstra beregning."], ["Hvor længe venter min chauffør i lufthavnen?", "De første 90 minutter efter landing er inkluderet uden beregning, og tidsvinduet flyttes automatisk, hvis dit fly er forsinket."], ["Hvordan betaler jeg for transferen?", "Kontant til din chauffør ved rejsens start - den faste pris fra din bestilling, pr. køretøj."]] },
  es: { home: "Inicio", routes: "Rutas de traslado", priceHeading: "Precios fijos de traslado", included: "Incluido en el precio", duration: "Tiempo estimado", distance: "Distancia", from: "Precio desde", book: "Reserve su traslado", faq: "Preguntas frecuentes", other: "Otros traslados del Aeropuerto de Antalya", campaign: "Hay precios especiales online disponibles para todas las rutas de traslado.", contact: "Contáctenos por WhatsApp para reservas y consultas.", privacy: "Privacidad", imprint: "Aviso legal", privacyUrl: "/privacy/", imprintUrl: "/impressum.html", vito: "Mercedes Vito · hasta 6 pasajeros", sprinter: "Mercedes Sprinter · hasta 12 pasajeros", intro: (name: string, duration: string, distance: string) => `El trayecto de ${distance} desde el Aeropuerto de Antalya a ${name} dura aproximadamente ${duration} con tráfico normal. Su chófer le recibe en llegadas y le lleva directamente a su alojamiento.`, items: ["Recepción personal", "Seguimiento de vuelos en tiempo real", "Aparcamiento y espera en el aeropuerto", "Asistencia con el equipaje y agua embotellada", "Silla infantil gratuita bajo petición"], faqItems: (name: string, price: number, duration: string) => [[`¿Cuánto dura el traslado del Aeropuerto de Antalya a ${name}?`, `El trayecto dura aproximadamente ${duration} con tráfico normal.`], [`¿Cuál es el precio fijo del traslado a ${name}?`, `Los precios del Mercedes Vito comienzan desde €${price} por vehículo. El total confirmado se muestra al reservar.`], ["¿Qué ocurre si mi vuelo se retrasa?", "Seguimos su vuelo en tiempo real y ajustamos la hora de encuentro sin coste adicional."], ["¿Cuánto tiempo espera mi chófer en el aeropuerto?", "Los primeros 90 minutos tras el aterrizaje están incluidos de forma gratuita, y el margen se ajusta automáticamente si su vuelo se retrasa."], ["¿Cómo pago el traslado?", "En efectivo a su chófer al inicio del trayecto: el precio fijo de su reserva, por vehículo."]] },
  el: { home: "Αρχική", routes: "Διαδρομές μεταφοράς", priceHeading: "Σταθερές τιμές μεταφοράς", included: "Περιλαμβάνεται στην τιμή", duration: "Εκτιμώμενος χρόνος", distance: "Απόσταση", from: "Τιμή από", book: "Κλείστε τη μεταφορά σας", faq: "Συχνές ερωτήσεις", other: "Άλλες μεταφορές από το Αεροδρόμιο Αντάλια", campaign: "Ειδικές διαδικτυακές τιμές είναι διαθέσιμες για όλες τις διαδρομές μεταφοράς.", contact: "Επικοινωνήστε μαζί μας στο WhatsApp για κρατήσεις και ερωτήσεις.", privacy: "Απόρρητο", imprint: "Νομικές πληροφορίες", privacyUrl: "/privacy/", imprintUrl: "/impressum.html", vito: "Mercedes Vito · έως 6 επιβάτες", sprinter: "Mercedes Sprinter · έως 12 επιβάτες", intro: (name: string, duration: string, distance: string) => `Το ταξίδι των ${distance} από το Αεροδρόμιο Αντάλια προς ${name} διαρκεί περίπου ${duration} υπό κανονικές συνθήκες κυκλοφορίας. Ο οδηγός σας σας υποδέχεται στις αφίξεις και σας μεταφέρει απευθείας στο κατάλυμά σας.`, items: ["Προσωπική υποδοχή Meet & Greet", "Παρακολούθηση πτήσης σε πραγματικό χρόνο", "Στάθμευση και αναμονή στο αεροδρόμιο", "Βοήθεια με τις αποσκευές και εμφιαλωμένο νερό", "Δωρεάν παιδικό κάθισμα κατόπιν αιτήματος"], faqItems: (name: string, price: number, duration: string) => [[`Πόσο διαρκεί η μεταφορά από το Αεροδρόμιο Αντάλια προς ${name};`, `Το ταξίδι διαρκεί περίπου ${duration} υπό κανονικές συνθήκες κυκλοφορίας.`], [`Ποια είναι η σταθερή τιμή μεταφοράς προς ${name};`, `Οι τιμές για Mercedes Vito ξεκινούν από €${price} ανά όχημα. Το επιβεβαιωμένο σύνολο εμφανίζεται κατά την κράτηση.`], ["Τι συμβαίνει αν η πτήση μου καθυστερήσει;", "Παρακολουθούμε την πτήση σας σε πραγματικό χρόνο και προσαρμόζουμε την ώρα συνάντησης χωρίς επιπλέον χρέωση."], ["Πόση ώρα περιμένει ο οδηγός μου στο αεροδρόμιο;", "Τα πρώτα 90 λεπτά μετά την προσγείωση περιλαμβάνονται δωρεάν, και το χρονικό περιθώριο μετατοπίζεται αυτόματα αν η πτήση σας καθυστερήσει."], ["Πώς πληρώνω για τη μεταφορά;", "Σε μετρητά στον οδηγό σας στην αρχή του ταξιδιού - τη σταθερή τιμή από την κράτησή σας, ανά όχημα."]],
  },
  he: { home: "דף הבית", routes: "מסלולי העברה", priceHeading: "מחירי העברה קבועים", included: "כלול במחיר", duration: "זמן משוער", distance: "מרחק", from: "מחיר החל מ-", book: "הזמינו את ההעברה שלכם", faq: "שאלות נפוצות", other: "העברות נוספות משדה התעופה אנטליה", campaign: "מחירים מיוחדים באינטרנט זמינים לכל מסלולי ההעברה.", contact: "צרו איתנו קשר ב-WhatsApp להזמנות ולשאלות.", privacy: "פרטיות", imprint: "פרטי חברה", privacyUrl: "/privacy/", imprintUrl: "/impressum.html", vito: "Mercedes Vito · עד 6 נוסעים", sprinter: "Mercedes Sprinter · עד 12 נוסעים", intro: (name: string, duration: string, distance: string) => `הנסיעה במרחק ${distance} משדה התעופה אנטליה אל ${name} אורכת כ-${duration} בתנועה רגילה. הנהג שלכם מקבל את פניכם באולם הנוסעים ונוסע ישירות אל מקום הלינה שלכם.`, items: ["קבלת פנים אישית", "מעקב טיסות בזמן אמת", "חניה והמתנה בשדה התעופה", "סיוע במטען ובקבוקי מים", "כיסא בטיחות לילד ללא תשלום לפי בקשה"], faqItems: (name: string, price: number, duration: string) => [[`כמה זמן אורכת ההעברה משדה התעופה אנטליה אל ${name}?`, `הנסיעה אורכת כ-${duration} בתנועה רגילה.`], [`מהו המחיר הקבוע של ההעברה אל ${name}?`, `מחירי Mercedes Vito מתחילים מ-€${price} לרכב. הסכום הכולל המאושר מוצג בעת ההזמנה.`], ["מה קורה אם הטיסה שלי מתעכבת?", "אנו עוקבים אחר הטיסה שלכם בזמן אמת ומתאימים את שעת המפגש ללא תוספת תשלום."], ["כמה זמן ממתין הנהג שלי בשדה התעופה?", "90 הדקות הראשונות לאחר הנחיתה כלולות ללא תשלום, וחלון ההמתנה זז אוטומטית אם הטיסה מתעכבת."], ["כיצד אני משלם עבור ההעברה?", "במזומן לנהג בתחילת הנסיעה - המחיר הקבוע מתוך ההזמנה שלכם, לכל רכב."]],
  },
  hu: { home: "Főoldal", routes: "Transzfer útvonalak", priceHeading: "Fix transzfer árak", included: "Az árban benne van", duration: "Becsült idő", distance: "Távolság", from: "Ár ettől", book: "Foglalja le transzferét", faq: "Gyakran ismételt kérdések", other: "További antalyai reptéri transzferek", campaign: "Minden transzfer útvonalra online kedvezményes árazás érhető el.", contact: "Foglalásokkal és kérdésekkel kapcsolatban vegye fel velünk a kapcsolatot WhatsApp-on.", privacy: "Adatvédelem", imprint: "Impresszum", privacyUrl: "/privacy/", imprintUrl: "/impressum.html", vito: "Mercedes Vito · legfeljebb 6 utas", sprinter: "Mercedes Sprinter · legfeljebb 12 utas", intro: (name: string, duration: string, distance: string) => `Az antalyai repülőtérről ${name} felé vezető ${distance} út normál forgalomban körülbelül ${duration} tart. Sofőrje a megérkezési csarnokban fogadja Önt, és közvetlenül a szállásához viszi.`, items: ["Személyes Meet & Greet fogadás", "Valós idejű járatkövetés", "Reptéri parkolás és várakozás", "Csomagsegítség és palackozott víz", "Ingyenes gyermekülés kérésre"], faqItems: (name: string, price: number, duration: string) => [[`Mennyi ideig tart a transzfer az antalyai repülőtérről ${name} felé?`, `Az út normál forgalomban körülbelül ${duration} tart.`], [`Mennyi a fix transzfer ára ${name} felé?`, `A Mercedes Vito árai járművenként €${price}-tól kezdődnek. A megerősített végösszeg a foglaláskor jelenik meg.`], ["Mi történik, ha a járatom késik?", "Valós időben követjük a járatát, és extra költség nélkül igazítjuk a találkozás időpontját."], ["Meddig vár a sofőröm a repülőtéren?", "A leszállás utáni első 90 perc ingyenesen benne van, és az időablak automatikusan eltolódik, ha a járata késik."], ["Hogyan fizetek a transzferért?", "Készpénzben a sofőrnek az út elején – a foglalásból származó fix ár, járművenként."]],
  },
  it: { home: "Home", routes: "Percorsi di transfer", priceHeading: "Prezzi fissi dei transfer", included: "Incluso nel prezzo", duration: "Tempo stimato", distance: "Distanza", from: "Prezzo da", book: "Prenota il tuo transfer", faq: "Domande frequenti", other: "Altri transfer dall'Aeroporto di Antalya", campaign: "Prezzi speciali online disponibili per tutti i percorsi di transfer.", contact: "Contattaci su WhatsApp per prenotazioni e domande.", privacy: "Privacy", imprint: "Note legali", privacyUrl: "/privacy/", imprintUrl: "/impressum.html", vito: "Mercedes Vito · fino a 6 passeggeri", sprinter: "Mercedes Sprinter · fino a 12 passeggeri", intro: (name: string, duration: string, distance: string) => `Il viaggio di ${distance} dall'Aeroporto di Antalya a ${name} dura circa ${duration} con traffico normale. Il tuo autista ti accoglie agli arrivi e ti porta direttamente al tuo alloggio.`, items: ["Accoglienza personale Meet & Greet", "Monitoraggio del volo in tempo reale", "Parcheggio e attesa in aeroporto", "Assistenza bagagli e acqua in bottiglia", "Seggiolino per bambini gratuito su richiesta"], faqItems: (name: string, price: number, duration: string) => [[`Quanto dura il transfer dall'Aeroporto di Antalya a ${name}?`, `Il viaggio dura circa ${duration} con traffico normale.`], [`Qual è il prezzo fisso del transfer per ${name}?`, `I prezzi Mercedes Vito partono da €${price} per veicolo. Il totale confermato viene mostrato al momento della prenotazione.`], ["Cosa succede se il mio volo è in ritardo?", "Monitoriamo il tuo volo in tempo reale e adeguiamo l'orario dell'incontro senza costi aggiuntivi."], ["Quanto tempo aspetta il mio autista in aeroporto?", "I primi 90 minuti dopo l'atterraggio sono inclusi gratuitamente, e la finestra si sposta automaticamente se il tuo volo è in ritardo."], ["Come pago il transfer?", "In contanti al tuo autista all'inizio del viaggio - il prezzo fisso della tua prenotazione, per veicolo."]],
  },
  ja: { home: "ホーム", routes: "送迎ルート", priceHeading: "固定送迎料金", included: "料金に含まれるもの", duration: "所要時間の目安", distance: "距離", from: "料金", book: "送迎を予約する", faq: "よくある質問", other: "その他のアンタルヤ空港送迎", campaign: "すべての送迎ルートでオンライン特別料金をご利用いただけます。", contact: "ご予約やご質問はWhatsAppでお問い合わせください。", privacy: "プライバシー", imprint: "会社概要", privacyUrl: "/privacy/", imprintUrl: "/impressum.html", vito: "Mercedes Vito · 最大6名", sprinter: "Mercedes Sprinter · 最大12名", intro: (name: string, duration: string, distance: string) => `アンタルヤ空港から${name}までの${distance}の道のりは、通常の交通状況で約${duration}かかります。運転手が到着ロビーでお迎えし、宿泊先まで直接お送りします。`, items: ["個別のミート＆グリート", "リアルタイムのフライト追跡", "空港での駐車と待機", "手荷物のお手伝いとミネラルウォーター", "ご要望に応じた無料チャイルドシート"], faqItems: (name: string, price: number, duration: string) => [[`アンタルヤ空港から${name}までの送迎はどのくらいかかりますか？`, `通常の交通状況で所要時間は約${duration}です。`], [`${name}への固定送迎料金はいくらですか？`, `Mercedes Vitoの料金は1台あたり€${price}からです。確定合計金額は予約時に表示されます。`], ["フライトが遅延した場合はどうなりますか？", "私たちはお客様のフライトをリアルタイムで追跡し、追加料金なしでお迎え時間を調整します。"], ["運転手は空港でどのくらい待ちますか？", "着陸後の最初の90分は無料に含まれており、フライトが遅延した場合は自動的に時間枠が移動します。"], ["送迎料金の支払い方法は？", "旅程開始時に運転手へ現金でお支払いください。予約時の固定料金、1台あたりの金額です。"]] },
  ko: { home: "홈", routes: "이동 노선", priceHeading: "정찰제 이동 요금", included: "요금에 포함된 사항", duration: "예상 소요 시간", distance: "거리", from: "요금 시작가", book: "이동 예약하기", faq: "자주 묻는 질문", other: "기타 안탈리아 공항 이동 서비스", campaign: "모든 이동 노선에 온라인 특별 요금이 제공됩니다.", contact: "예약 및 문의는 WhatsApp으로 연락 주세요.", privacy: "개인정보 보호정책", imprint: "임프린트", privacyUrl: "/privacy/", imprintUrl: "/impressum.html", vito: "Mercedes Vito · 최대 6명 탑승", sprinter: "Mercedes Sprinter · 최대 12명 탑승", intro: (name: string, duration: string, distance: string) => `안탈리아 공항에서 ${name}까지 ${distance} 거리는 일반적인 교통 상황에서 약 ${duration} 소요됩니다. 기사님이 도착장에서 여러분을 맞이하고 숙소까지 곧바로 모셔다 드립니다.`, items: ["개인 미팅 서비스", "실시간 항공편 추적", "공항 주차 및 대기", "수하물 지원 및 생수 제공", "요청 시 무료 유아용 카시트"], faqItems: (name: string, price: number, duration: string) => [[`안탈리아 공항에서 ${name}까지 이동 시간은 얼마나 걸리나요?`, `일반적인 교통 상황에서 약 ${duration} 소요됩니다.`], [`${name}까지의 정찰제 이동 요금은 얼마인가요?`, `Mercedes Vito 요금은 차량당 €${price}부터 시작합니다. 확정 총액은 예약 시 표시됩니다.`], ["항공편이 지연되면 어떻게 되나요?", "실시간으로 항공편을 추적하며 추가 요금 없이 미팅 시간을 조정합니다."], ["기사님은 공항에서 얼마나 대기하나요?", "착륙 후 첫 90분은 무료로 포함되며, 항공편이 지연되면 대기 시간이 자동으로 조정됩니다."], ["이동 요금은 어떻게 결제하나요?", "이동 시작 시 기사님께 현금으로 결제합니다 - 예약 시 확정된 차량당 정찰제 요금입니다."]],
  },
  pt: { home: "Início", routes: "Rotas de transfer", priceHeading: "Preços fixos de transfer", included: "Incluído no preço", duration: "Tempo estimado", distance: "Distância", from: "Preço desde", book: "Reserve o seu transfer", faq: "Perguntas frequentes", other: "Outros transfers do Aeroporto de Antalya", campaign: "Preços especiais online disponíveis para todas as rotas de transfer.", contact: "Contacte-nos pelo WhatsApp para reservas e questões.", privacy: "Privacidade", imprint: "Ficha técnica", privacyUrl: "/privacy/", imprintUrl: "/impressum.html", vito: "Mercedes Vito · até 6 passageiros", sprinter: "Mercedes Sprinter · até 12 passageiros", intro: (name: string, duration: string, distance: string) => `A viagem de ${distance} do Aeroporto de Antalya para ${name} demora aproximadamente ${duration} em trânsito normal. O seu motorista recebe-o nas chegadas e conduz diretamente até ao seu alojamento.`, items: ["Receção personalizada", "Monitorização de voos em tempo real", "Estacionamento e espera no aeroporto", "Assistência com bagagem e água engarrafada", "Cadeira de criança gratuita mediante pedido"], faqItems: (name: string, price: number, duration: string) => [[`Quanto tempo demora o transfer do Aeroporto de Antalya para ${name}?`, `A viagem demora aproximadamente ${duration} em trânsito normal.`], [`Qual é o preço fixo do transfer para ${name}?`, `Os preços do Mercedes Vito começam em €${price} por veículo. O total confirmado é apresentado na reserva.`], ["O que acontece se o meu voo tiver atraso?", "Monitorizamos o seu voo em tempo real e ajustamos a hora do encontro sem custos adicionais."], ["Quanto tempo espera o meu motorista no aeroporto?", "Os primeiros 90 minutos após a aterragem estão incluídos gratuitamente, e o período ajusta-se automaticamente se o seu voo tiver atraso."], ["Como pago o transfer?", "Em dinheiro ao seu motorista no início da viagem - o preço fixo da sua reserva, por veículo."]],
  },
  ro: { home: "Acasă", routes: "Rute de transfer", priceHeading: "Prețuri fixe de transfer", included: "Inclus în preț", duration: "Timp estimat", distance: "Distanță", from: "Preț de la", book: "Rezervați transferul", faq: "Întrebări frecvente", other: "Alte transferuri de la Aeroportul Antalya", campaign: "Prețuri speciale online sunt disponibile pentru toate rutele de transfer.", contact: "Contactați-ne pe WhatsApp pentru rezervări și întrebări.", privacy: "Confidențialitate", imprint: "Imprint", privacyUrl: "/privacy/", imprintUrl: "/impressum.html", vito: "Mercedes Vito · până la 6 pasageri", sprinter: "Mercedes Sprinter · până la 12 pasageri", intro: (name: string, duration: string, distance: string) => `Călătoria de ${distance} de la Aeroportul Antalya la ${name} durează aproximativ ${duration} în condiții normale de trafic. Șoferul dumneavoastră vă întâmpină la sosiri și vă conduce direct la cazare.`, items: ["Întâmpinare personală", "Urmărirea zborului în timp real", "Parcare și așteptare la aeroport", "Asistență pentru bagaje și apă îmbuteliată", "Scaun pentru copil gratuit la cerere"], faqItems: (name: string, price: number, duration: string) => [[`Cât durează transferul de la Aeroportul Antalya la ${name}?`, `Călătoria durează aproximativ ${duration} în condiții normale de trafic.`], [`Care este prețul fix al transferului către ${name}?`, `Prețurile Mercedes Vito încep de la €${price} per vehicul. Totalul confirmat este afișat la momentul rezervării.`], ["Ce se întâmplă dacă zborul meu întârzie?", "Vă urmărim zborul în timp real și ajustăm ora întâlnirii fără costuri suplimentare."], ["Cât timp așteaptă șoferul la aeroport?", "Primele 90 de minute după aterizare sunt incluse gratuit, iar intervalul se ajustează automat dacă zborul dumneavoastră întârzie."], ["Cum plătesc transferul?", "În numerar șoferului la începutul călătoriei - prețul fix din rezervarea dumneavoastră, per vehicul."]],
  },

  en: {
    home: "Home", routes: "Transfer routes", priceHeading: "Fixed transfer prices", included: "Included in the price", duration: "Estimated time", distance: "Distance", from: "Price from", book: "Book your transfer", faq: "Frequently asked questions", other: "Other Antalya Airport transfers", campaign: "Online special pricing is available for all transfer routes.", contact: "Contact us on WhatsApp for bookings and questions.", privacy: "Privacy", imprint: "Imprint", privacyUrl: "/privacy/", imprintUrl: "/impressum.html", vito: "Mercedes Vito · up to 6 passengers", sprinter: "Mercedes Sprinter · up to 12 passengers", intro: (name: string, duration: string, distance: string) => `The ${distance} journey from Antalya Airport to ${name} takes approximately ${duration} in normal traffic. Your chauffeur meets you in arrivals and drives directly to your accommodation.`, items: ["Personal meet and greet", "Real-time flight tracking", "Airport parking and waiting", "Luggage assistance and bottled water", "Free child seat on request"], faqItems: (name: string, price: number, duration: string) => [[`How long is the transfer from Antalya Airport to ${name}?`, `The journey takes approximately ${duration} in normal traffic.`], [`What is the fixed transfer price to ${name}?`, `Mercedes Vito prices start from €${price} per vehicle. The confirmed total is shown when booking.`], ["What happens if my flight is delayed?", "We track your flight in real time and adjust the meeting time at no extra charge."], ["How long does my chauffeur wait at the airport?", "The first 90 minutes after landing are included free of charge, and the window moves automatically if your flight is delayed."], ["How do I pay for the transfer?", "In cash to your chauffeur at the start of the journey - the fixed price from your booking, per vehicle."]],
  },
  de: {
    home: "Startseite", routes: "Transferrouten", priceHeading: "Feste Transferpreise", included: "Im Preis enthalten", duration: "Geschätzte Fahrzeit", distance: "Entfernung", from: "Preis ab", book: "Transfer buchen", faq: "Häufig gestellte Fragen", other: "Weitere Transfers vom Flughafen Antalya", campaign: "Online-Spezialpreise sind für alle Transferstrecken verfügbar.", contact: "Für Buchungen und Fragen erreichen Sie uns über WhatsApp.", privacy: "Datenschutz", imprint: "Impressum", privacyUrl: "/de/datenschutz/", imprintUrl: "/de/impressum/", vito: "Mercedes Vito · bis 6 Personen", sprinter: "Mercedes Sprinter · bis 12 Personen", intro: (name: string, duration: string, distance: string) => `Die ${distance} lange Fahrt vom Flughafen Antalya nach ${name} dauert bei normalem Verkehr ungefähr ${duration}. Nachdem Sie Ihr Gepäck abgeholt haben, gehen Sie bitte zum Meet & Greet Bereich J / 777. Unser Flughafen-Team findet Ihre Buchung und bringt Sie mit Ihrem Fahrer zusammen; anschließend fahren Sie direkt zu Ihrer Unterkunft.`, items: ["Persönlicher Empfang", "Flugverfolgung in Echtzeit", "Flughafenparken und Wartezeit", "Gepäckhilfe und Mineralwasser", "Kostenloser Kindersitz auf Wunsch"], faqItems: (name: string, price: number, duration: string) => [[`Wie lange dauert der Transfer vom Flughafen Antalya nach ${name}?`, `Die Fahrt dauert bei normalem Verkehr ungefähr ${duration}.`], [`Was kostet der Festpreis-Transfer nach ${name}?`, `Die Preise für einen Mercedes Vito beginnen bei €${price} pro Fahrzeug. Der bestätigte Gesamtpreis wird bei der Buchung angezeigt.`], ["Was passiert bei einer Flugverspätung?", "Wir verfolgen Ihren Flug in Echtzeit und passen die Abholzeit ohne Aufpreis an."], ["Wie lange wartet mein Chauffeur am Flughafen?", "Die ersten 90 Minuten nach der Landung sind kostenfrei enthalten, und bei Flugverspätungen verschiebt sich dieses Zeitfenster automatisch."], ["Wie bezahle ich den Transfer?", "Bar an Ihren Chauffeur zu Beginn der Fahrt - zum Festpreis aus Ihrer Buchung, pro Fahrzeug."]],
  },
  tr: {
    home: "Ana sayfa", routes: "Transfer rotaları", priceHeading: "Sabit transfer fiyatları", included: "Fiyata dahil olanlar", duration: "Tahmini süre", distance: "Mesafe", from: "Başlangıç fiyatı", book: "Transferinizi ayırtın", faq: "Sık sorulan sorular", other: "Diğer Antalya Havalimanı transferleri", campaign: "Online'a özel fiyatlar tüm transfer rotalarında sunulmaktadır.", contact: "Rezervasyon ve sorularınız için WhatsApp üzerinden bize ulaşın.", privacy: "Gizlilik", imprint: "Künye", privacyUrl: "/tr/gizlilik/", imprintUrl: "/tr/kunye/", vito: "Mercedes Vito · 6 yolcuya kadar", sprinter: "Mercedes Sprinter · 12 yolcuya kadar", intro: (name: string, duration: string, distance: string) => `Antalya Havalimanı ile ${name} arasındaki ${distance} mesafeli yolculuk normal trafik koşullarında yaklaşık ${duration} sürer. Şoförünüz sizi gelen yolcu salonunda karşılar ve doğrudan konaklama adresinize götürür.`, items: ["Kişisel karşılama", "Gerçek zamanlı uçuş takibi", "Havalimanı otoparkı ve bekleme", "Bagaj yardımı ve şişe su", "Talep üzerine ücretsiz çocuk koltuğu"], faqItems: (name: string, price: number, duration: string) => [[`Antalya Havalimanı ile ${name} arası transfer ne kadar sürer?`, `Normal trafik koşullarında yolculuk yaklaşık ${duration} sürer. Trafik ve otel konumu süreyi etkileyebilir.`], [`${name} transferinin sabit fiyatı nedir?`, `Mercedes Vito fiyatları araç başına €${price}'dan başlar. Kesin toplam rezervasyon sırasında gösterilir.`], ["Uçuşum gecikirse ne olur?", "Uçuşunuzu gerçek zamanlı takip eder, karşılama saatini ücretsiz olarak güncelleriz."], ["Şoförüm havalimanında ne kadar bekler?", "İnişten sonraki ilk 90 dakika ücretsiz olarak fiyata dahildir; uçuş gecikmelerinde bu süre otomatik olarak kayar."], ["Transfer ödemesini nasıl yapıyorum?", "Yolculuğun başında şoförünüze nakit olarak - rezervasyonda gördüğünüz sabit fiyat, araç başına."]],
  },
  ru: {
    home: "Главная", routes: "Маршруты трансфера", priceHeading: "Фиксированные цены", included: "В стоимость включено", duration: "Время в пути", distance: "Расстояние", from: "Цена от", book: "Забронировать трансфер", faq: "Частые вопросы", other: "Другие трансферы из аэропорта Антальи", campaign: "Специальные онлайн-тарифы доступны для всех маршрутов трансфера.", contact: "Для бронирования и вопросов напишите нам в WhatsApp.", privacy: "Конфиденциальность", imprint: "Правовая информация", privacyUrl: "/ru/privacy/", imprintUrl: "/ru/impressum/", vito: "Mercedes Vito · до 6 пассажиров", sprinter: "Mercedes Sprinter · до 12 пассажиров", intro: (name: string, duration: string, distance: string) => `Поездка из аэропорта Антальи в ${name} на расстояние ${distance} занимает примерно ${duration} при обычном движении. Водитель встретит вас в зале прилёта и отвезёт прямо к месту проживания.`, items: ["Личная встреча", "Отслеживание рейса в реальном времени", "Парковка и ожидание в аэропорту", "Помощь с багажом и вода", "Бесплатное детское кресло по запросу"], faqItems: (name: string, price: number, duration: string) => [[`Сколько длится трансфер из аэропорта Антальи в ${name}?`, `При обычном движении поездка занимает около ${duration}. Точное время зависит от дорожной ситуации и расположения отеля.`], [`Сколько стоит трансфер в ${name}?`, `Стоимость Mercedes Vito начинается от €${price} за автомобиль. Итоговая фиксированная цена показывается при бронировании.`], ["Что произойдёт при задержке рейса?", "Мы отслеживаем рейс в реальном времени и бесплатно корректируем время встречи."], ["Сколько водитель ждёт в аэропорту?", "Первые 90 минут после посадки включены в стоимость, а при задержке рейса отсчёт сдвигается автоматически."], ["Как оплатить трансфер?", "Наличными водителю в начале поездки - по фиксированной цене из бронирования, за автомобиль."]],
  },
  fr: {
    home: "Accueil", routes: "Routes de transfert", priceHeading: "Prix fixes de transfert", included: "Inclus dans le prix", duration: "Durée estimée", distance: "Distance", from: "Prix à partir de", book: "Réserver votre transfert", faq: "Questions fréquentes", other: "Autres transferts depuis l'aéroport d'Antalya", campaign: "Des tarifs spéciaux en ligne sont disponibles pour toutes les routes de transfert.", contact: "Contactez-nous sur WhatsApp pour les réservations et questions.", privacy: "Confidentialité", imprint: "Mentions légales", privacyUrl: "/fr/privacy/", imprintUrl: "/fr/impressum/", vito: "Mercedes Vito · jusqu'à 6 passagers", sprinter: "Mercedes Sprinter · jusqu'à 12 passagers", intro: (name: string, duration: string, distance: string) => `Le trajet de ${distance} depuis l'aéroport d'Antalya jusqu'à ${name} dure environ ${duration} en trafic normal. Après avoir récupéré vos bagages, rendez-vous dans la zone Meet & Greet J / 777. Notre équipe identifiera votre réservation et vous mettra en contact avec votre chauffeur.`, items: ["Accueil personnalisé", "Suivi du vol en temps réel", "Parking aéroport et attente inclus", "Aide aux bagages et eau en bouteille", "Siège enfant gratuit sur demande"], faqItems: (name: string, price: number, duration: string) => [[`Combien de temps dure le transfert de l'aéroport d'Antalya vers ${name} ?`, `Le trajet dure environ ${duration} en trafic normal.`], [`Quel est le prix fixe du transfert vers ${name} ?`, `Les prix Mercedes Vito commencent à €${price} par véhicule. Le montant total confirmé est affiché lors de la réservation.`], ["Que se passe-t-il si mon vol est retardé ?", "Nous suivons votre vol en temps réel et ajustons l'heure de prise en charge sans frais supplémentaires."], ["Combien de temps mon chauffeur attend-il à l'aéroport ?", "Les 90 premières minutes après l'atterrissage sont incluses sans frais, et ce délai se décale automatiquement en cas de retard de vol."], ["Comment régler le transfert ?", "En espèces à votre chauffeur au début du trajet - au prix fixe de votre réservation, par véhicule."]],
  },
  cs: {
    home: "Domů", routes: "Trasy transferů", priceHeading: "Pevné ceny transferů", included: "Co je zahrnuto v ceně", duration: "Odhadovaný čas", distance: "Vzdálenost", from: "Cena od", book: "Rezervovat transfer", faq: "Často kladené dotazy", other: "Další transfery z letiště Antalya", campaign: "Speciální online ceny jsou dostupné pro všechny transferové trasy.", contact: "Pro rezervace a dotazy nás kontaktujte na WhatsApp.", privacy: "Ochrana soukromí", imprint: "Impressum", privacyUrl: "/cs/privacy/", imprintUrl: "/cs/impressum/", vito: "Mercedes Vito · až 6 cestujících", sprinter: "Mercedes Sprinter · až 12 cestujících", intro: (name: string, duration: string, distance: string) => `Cesta z letiště Antalya do ${name}, vzdálená ${distance}, trvá přibližně ${duration} při běžném provozu. Váš šofér vás uvítá v příletové hale a odveze vás přímo do ubytování.`, items: ["Osobní uvítání", "Sledování letů v reálném čase", "Parkoviště na letišti a čekání", "Pomoc se zavazadly a balená voda", "Bezplatná dětská sedačka na vyžádání"], faqItems: (name: string, price: number, duration: string) => [[`Jak dlouho trvá transfer z letiště Antalya do ${name}?`, `Cesta trvá přibližně ${duration} při běžném provozu.`], [`Jaká je pevná cena transferu do ${name}?`, `Ceny Mercedes Vito začínají od €${price} za vozidlo. Potvrzená celková cena je zobrazena při rezervaci.`], ["Co se stane, když má můj let zpoždění?", "Sledujeme váš let v reálném čase a upravujeme čas setkání bez příplatku."], ["Jak dlouho na mě šofér na letišti čeká?", "Prvních 90 minut po přistání je zdarma v ceně a při zpoždění letu se tento interval automaticky posouvá."], ["Jak transfer zaplatím?", "V hotovosti šoférovi na začátku jízdy - pevnou cenou z vaší rezervace, za vozidlo."]],
  },
  uk: {
    home: "Головна", routes: "Маршрути трансферу", priceHeading: "Фіксовані ціни трансферу", included: "Що входить у ціну", duration: "Орієнтовний час", distance: "Відстань", from: "Ціна від", book: "Забронювати трансфер", faq: "Часті запитання", other: "Інші трансфери з аеропорту Анталії", campaign: "Спеціальні онлайн-ціни доступні для всіх маршрутів трансферу.", contact: "Для бронювання та запитань пишіть нам у WhatsApp.", privacy: "Конфіденційність", imprint: "Правова інформація", privacyUrl: "/uk/privacy/", imprintUrl: "/uk/impressum/", vito: "Mercedes Vito · до 6 пасажирів", sprinter: "Mercedes Sprinter · до 12 пасажирів", intro: (name: string, duration: string, distance: string) => `Поїздка з аеропорту Анталії до ${name} відстанню ${distance} займає приблизно ${duration} за звичайного руху. Ваш водій зустріне вас у залі прильоту та відвезе прямо до місця проживання.`, items: ["Особиста зустріч", "Відстеження рейсу в реальному часі", "Паркування та очікування в аеропорту", "Допомога з багажем і вода", "Безкоштовне дитяче крісло за запитом"], faqItems: (name: string, price: number, duration: string) => [[`Скільки триває трансфер з аеропорту Анталії до ${name}?`, `За звичайного руху поїздка займає близько ${duration}.`], [`Яка фіксована ціна трансферу до ${name}?`, `Ціни на Mercedes Vito починаються від €${price} за автомобіль. Підтверджена загальна сума показується під час бронювання.`], ["Що станеться, якщо мій рейс затримається?", "Ми відстежуємо ваш рейс у реальному часі та безкоштовно коригуємо час зустрічі."], ["Скільки водій чекає в аеропорту?", "Перші 90 хвилин після посадки включені у вартість, а в разі затримки рейсу відлік зміщується автоматично."], ["Як оплатити трансфер?", "Готівкою водієві на початку поїздки - за фіксованою ціною з бронювання, за автомобіль."]],
  },
  ur: {
    home: "ہوم", routes: "ٹرانسفر روٹس", priceHeading: "مقررہ ٹرانسفر قیمتیں", included: "قیمت میں شامل", duration: "تخمینی وقت", distance: "فاصلہ", from: "قیمت شروع", book: "اپنا ٹرانسفر بک کریں", faq: "اکثر پوچھے گئے سوالات", other: "انطالیہ ایئرپورٹ کے دیگر ٹرانسفرز", campaign: "تمام ٹرانسفر روٹس کے لیے آن لائن خصوصی قیمتیں دستیاب ہیں۔", contact: "بکنگ اور سوالات کے لیے WhatsApp پر ہم سے رابطہ کریں۔", privacy: "پرائیویسی", imprint: "قانونی معلومات", privacyUrl: "/ur/privacy/", imprintUrl: "/ur/impressum/", vito: "Mercedes Vito · 6 مسافروں تک", sprinter: "Mercedes Sprinter · 12 مسافروں تک", intro: (name: string, duration: string, distance: string) => `انطالیہ ایئرپورٹ سے ${name} تک ${distance} کا سفر عام ٹریفک میں تقریباً ${duration} لیتا ہے۔ آپ کا ڈرائیور آپ کو آمد ہال میں ملے گا اور براہ راست آپ کی رہائش گاہ تک لے جائے گا۔`, items: ["ذاتی استقبال", "حقیقی وقت میں پرواز کی نگرانی", "ایئرپورٹ پارکنگ اور انتظار", "سامان میں مدد اور بوتل بند پانی", "درخواست پر مفت بچوں کی سیٹ"], faqItems: (name: string, price: number, duration: string) => [[`انطالیہ ایئرپورٹ سے ${name} تک ٹرانسفر میں کتنا وقت لگتا ہے؟`, `عام ٹریفک میں سفر تقریباً ${duration} لیتا ہے۔`], [`${name} تک ٹرانسفر کی مقررہ قیمت کیا ہے؟`, `Mercedes Vito کی قیمتیں €${price} فی گاڑی سے شروع ہوتی ہیں۔ تصدیق شدہ کل رقم بکنگ کے وقت دکھائی جاتی ہے۔`], ["اگر میری پرواز میں تاخیر ہو جائے تو کیا ہوگا؟", "ہم آپ کی پرواز کو حقیقی وقت میں ٹریک کرتے ہیں اور بغیر کسی اضافی چارج کے ملاقات کا وقت ایڈجسٹ کرتے ہیں۔"], ["میرا ڈرائیور ایئرپورٹ پر کتنی دیر انتظار کرتا ہے؟", "لینڈنگ کے بعد پہلے 90 منٹ مفت شامل ہیں، اور پرواز میں تاخیر کی صورت میں یہ دورانیہ خودکار طور پر آگے کھسک جاتا ہے۔"], ["ٹرانسفر کی ادائیگی کیسے کروں؟", "سفر کے آغاز پر ڈرائیور کو نقد - بکنگ کی مقررہ قیمت، فی گاڑی۔"]],
  },
  pl: {
    home: "Strona główna", routes: "Trasy transferów", priceHeading: "Stałe ceny transferów", included: "Wliczone w cenę", duration: "Szacowany czas", distance: "Odległość", from: "Cena od", book: "Zarezerwuj transfer", faq: "Często zadawane pytania", other: "Inne transfery z lotniska Antalya", campaign: "Specjalne ceny online są dostępne dla wszystkich tras transferu.", contact: "Skontaktuj się z nami przez WhatsApp w sprawie rezerwacji i pytań.", privacy: "Prywatność", imprint: "Nota prawna", privacyUrl: "/privacy/", imprintUrl: "/impressum.html", vito: "Mercedes Vito · do 6 pasażerów", sprinter: "Mercedes Sprinter · do 12 pasażerów", intro: (name: string, duration: string, distance: string) => `Podróż o długości ${distance} z lotniska Antalya do ${name} trwa około ${duration} przy normalnym ruchu. Kierowca powita Cię w hali przylotów i zawiezie bezpośrednio do miejsca zakwaterowania.`, items: ["Osobiste powitanie", "Śledzenie lotu w czasie rzeczywistym", "Parking i oczekiwanie na lotnisku", "Pomoc z bagażem i woda butelkowana", "Bezpłatny fotelik dziecięcy na życzenie"], faqItems: (name: string, price: number, duration: string) => [[`Jak długo trwa transfer z lotniska Antalya do ${name}?`, `Przy normalnym ruchu podróż trwa około ${duration}.`], [`Jaka jest stała cena transferu do ${name}?`, `Ceny Mercedes Vito zaczynają się od €${price} za pojazd. Potwierdzona łączna kwota jest pokazywana podczas rezerwacji.`], ["Co się stanie, jeśli mój lot będzie opóźniony?", "Śledzimy Twój lot w czasie rzeczywistym i bez dodatkowych opłat dostosowujemy godzinę odbioru."], ["Jak długo kierowca czeka na lotnisku?", "Pierwsze 90 minut po wylądowaniu jest wliczone w cenę, a przy opóźnieniu lotu okno to przesuwa się automatycznie."], ["Jak zapłacić za transfer?", "Gotówką kierowcy na początku podróży - stała cena z rezerwacji, za pojazd."]],
  },
  nl: {
    home: "Home", routes: "Transferroutes", priceHeading: "Vaste transferprijzen", included: "Inbegrepen in de prijs", duration: "Geschatte tijd", distance: "Afstand", from: "Prijs vanaf", book: "Boek uw transfer", faq: "Veelgestelde vragen", other: "Andere transfers vanaf de luchthaven Antalya", campaign: "Speciale online prijzen zijn beschikbaar voor alle transferroutes.", contact: "Neem contact met ons op via WhatsApp voor boekingen en vragen.", privacy: "Privacy", imprint: "Colofon", privacyUrl: "/privacy/", imprintUrl: "/impressum.html", vito: "Mercedes Vito · tot 6 passagiers", sprinter: "Mercedes Sprinter · tot 12 passagiers", intro: (name: string, duration: string, distance: string) => `De rit van ${distance} van de luchthaven Antalya naar ${name} duurt ongeveer ${duration} bij normaal verkeer. Uw chauffeur ontvangt u in de aankomsthal en rijdt rechtstreeks naar uw accommodatie.`, items: ["Persoonlijke ontvangst", "Realtime vluchtvolging", "Parkeren en wachten op de luchthaven", "Bagagehulp en flessenwater", "Gratis kinderzitje op aanvraag"], faqItems: (name: string, price: number, duration: string) => [[`Hoe lang duurt de transfer van de luchthaven Antalya naar ${name}?`, `De rit duurt ongeveer ${duration} bij normaal verkeer.`], [`Wat is de vaste transferprijs naar ${name}?`, `Mercedes Vito-prijzen beginnen bij €${price} per voertuig. Het bevestigde totaal wordt getoond bij het boeken.`], ["Wat gebeurt er als mijn vlucht vertraging heeft?", "We volgen uw vlucht in realtime en passen de ophaaltijd zonder extra kosten aan."], ["Hoe lang wacht mijn chauffeur op de luchthaven?", "De eerste 90 minuten na de landing zijn kosteloos inbegrepen en dit tijdvenster schuift automatisch mee bij vertraging."], ["Hoe betaal ik de transfer?", "Contant aan uw chauffeur bij aanvang van de rit - de vaste prijs uit uw boeking, per voertuig."]],
  },
  ar: {
    home: "الرئيسية", routes: "مسارات النقل", priceHeading: "أسعار نقل ثابتة", included: "مشمول في السعر", duration: "الوقت المقدر", distance: "المسافة", from: "السعر من", book: "احجز نقلك", faq: "الأسئلة الشائعة", other: "خدمات نقل أخرى من مطار أنطاليا", campaign: "تتوفر أسعار خاصة عبر الإنترنت لجميع مسارات النقل.", contact: "تواصل معنا عبر واتساب للحجوزات والاستفسارات.", privacy: "الخصوصية", imprint: "معلومات قانونية", privacyUrl: "/privacy/", imprintUrl: "/impressum.html", vito: "مرسيدس فيتو · حتى 6 ركاب", sprinter: "مرسيدس سبرينتر · حتى 12 راكبًا", intro: (name: string, duration: string, distance: string) => `تستغرق رحلة المسافة ${distance} من مطار أنطاليا إلى ${name} حوالي ${duration} في حركة المرور العادية. يستقبلك سائقك في صالة الوصول ويقودك مباشرة إلى مكان إقامتك.`, items: ["استقبال شخصي", "تتبع الرحلة في الوقت الفعلي", "موقف وانتظار في المطار", "المساعدة في الأمتعة ومياه معبأة", "مقعد أطفال مجاني عند الطلب"], faqItems: (name: string, price: number, duration: string) => [[`كم يستغرق النقل من مطار أنطاليا إلى ${name}؟`, `تستغرق الرحلة حوالي ${duration} في حركة المرور العادية.`], [`ما هو السعر الثابت للنقل إلى ${name}؟`, `تبدأ أسعار مرسيدس فيتو من €${price} لكل مركبة. يظهر الإجمالي المؤكد عند الحجز.`], ["ماذا يحدث إذا تأخرت رحلتي؟", "نتتبع رحلتك في الوقت الفعلي ونعدّل وقت اللقاء دون أي رسوم إضافية."], ["كم ينتظر السائق في المطار؟", "أول 90 دقيقة بعد الهبوط مشمولة مجانًا، وتتحرك هذه المدة تلقائيًا مع أي تأخير في الرحلة."], ["كيف أدفع قيمة النقل؟", "نقدًا للسائق في بداية الرحلة - بالسعر الثابت من حجزك، لكل مركبة."]],
  },
  sv: {
    home: "Hem", routes: "Transferrutter", priceHeading: "Fasta transferpriser", included: "Ingår i priset", duration: "Beräknad tid", distance: "Avstånd", from: "Pris från", book: "Boka din transfer", faq: "Vanliga frågor", other: "Andra transfrar från Antalya flygplats", campaign: "Särskilda onlinepriser är tillgängliga för alla transferrutter.", contact: "Kontakta oss på WhatsApp för bokningar och frågor.", privacy: "Integritet", imprint: "Juridisk information", privacyUrl: "/privacy/", imprintUrl: "/impressum.html", vito: "Mercedes Vito · upp till 6 passagerare", sprinter: "Mercedes Sprinter · upp till 12 passagerare", intro: (name: string, duration: string, distance: string) => `Resan på ${distance} från Antalya flygplats till ${name} tar ungefär ${duration} vid normal trafik. Din chaufför möter dig i ankomsthallen och kör dig direkt till ditt boende.`, items: ["Personligt möte", "Flygbevakning i realtid", "Parkering och väntan på flygplatsen", "Bagagehjälp och vatten på flaska", "Gratis barnstol på begäran"], faqItems: (name: string, price: number, duration: string) => [[`Hur lång tid tar transfern från Antalya flygplats till ${name}?`, `Resan tar cirka ${duration} vid normal trafik.`], [`Vad är det fasta transferpriset till ${name}?`, `Mercedes Vito-priser börjar från €${price} per fordon. Den bekräftade summan visas vid bokning.`], ["Vad händer om mitt flyg är försenat?", "Vi spårar ditt flyg i realtid och justerar mötestiden utan extra kostnad."], ["Hur länge väntar chauffören på flygplatsen?", "De första 90 minuterna efter landning ingår utan kostnad, och tidsfönstret förskjuts automatiskt vid flygförsening."], ["Hur betalar jag transfern?", "Kontant till chauffören när resan börjar - det fasta priset från din bokning, per fordon."]],
  },
} as const;

export function TransferPage({ language, route }: { language: IndexableLanguage; route: LocalizedRoute }) {
  const text = copy[language];
  const seo = routeCopy(language);
  const prefix = language === "en" ? "" : `/${language}`;
  const homeHref = `${prefix}/`;
  const heading = seo.heading(route.name);
  const faq = text.faqItems(route.name, route.prices.vito, route.durationLabel);
  const germanHotels = language === "de" ? germanLandingHotels[route.slug] : undefined;
  const cataloguedHotels = language === "de" ? hotelsForRegion(route.slug) : [];
  const germanRegion = language === "de" ? germanRegionCopy[route.slug] : undefined;
  const germanFaq = germanHotels ? [
    ...faq,
    ["Wo treffe ich das Transfer-Team am Flughafen Antalya?", "Nachdem Sie Ihr Gepäck abgeholt haben, gehen Sie bitte zum Meet & Greet Bereich J / 777. Unser Flughafen-Team findet Ihre Buchung und bringt Sie mit Ihrem Fahrer zusammen."],
    ["Muss ich den Transfer im Voraus bezahlen?", "Nein. Eine Vorauszahlung ist nicht erforderlich. Sie zahlen den festen Gesamtpreis direkt beim Fahrer."],
    ["Ist ein Kindersitz verfügbar?", "Ja. Kindersitze stellen wir auf Wunsch kostenlos bereit. Bitte geben Sie Alter und Anzahl der Kinder bei der Buchung an."],
  ] : faq;

  return (
    <>
      <StaticPageHeader homeHref={homeHref} homeLabel={text.home} secondaryHref="#details" secondaryLabel={text.routes} tertiaryHref="#contact" tertiaryLabel="WhatsApp" ctaHref={`${homeHref}#booking`} ctaLabel={text.book} />
      <main>
        <section className="localized-route"><div className="eyebrow light"><span /><p>Antalya VIP Tourism</p></div><h1>{germanHotels ? `Flughafen Antalya → ${route.name} Privattransfer` : heading}</h1><p>{seo.description(route.name, route.prices.vito)}</p>{germanHotels ? <><a className="button button-gold" href={`${homeHref}#booking`}>Jetzt Transfer buchen</a><ul className="localized-trust"><li>Bis zu 7 Personen</li><li>Keine Vorauszahlung erforderlich</li><li>Zahlung direkt beim Fahrer</li><li>Fester Gesamtpreis ohne versteckte Gebühren</li><li>Kostenloser Kindersitz auf Anfrage</li><li>Flugüberwachung inklusive</li></ul></> : <p className="localized-campaign">{text.campaign}</p>}<div className="localized-stats"><div><strong>{route.durationLabel}</strong><span>{text.duration}</span></div><div><strong>{route.distance}</strong><span>{text.distance}</span></div><div><strong>€{route.prices.vito}</strong><span>{text.from}</span></div></div></section>
        <section className="localized-content" id="details"><div className="localized-grid"><div><h2>{germanHotels ? `Ihr privater Transfer nach ${route.name}` : heading}</h2><p>{text.intro(route.name, route.durationLabel, route.distance)}</p>{germanRegion && <><h3>Über {route.name}</h3><p>{germanRegion.about}</p><p>{germanRegion.routeDetails}</p></>}{germanHotels && <><p>Sie reisen ausschließlich mit Ihrer eigenen Gruppe direkt zu Ihrem Hotel in {route.name}. Kein Shuttle, keine fremden Fahrgäste und keine unnötigen Zwischenstopps – der feste Preis gilt für das gesamte Fahrzeug.</p><h3>Ihre Ankunft am Flughafen Antalya</h3><p>Nachdem Sie Ihr Gepäck abgeholt haben, gehen Sie bitte zum Meet & Greet Bereich J / 777. Unser Flughafen-Team findet Ihre Buchung und bringt Sie mit Ihrem Fahrer zusammen. Dank Flugüberwachung passen wir die Abholung bei einer Verspätung ohne Aufpreis an.</p><h3>Hin- und Rücktransfer</h3><p>Gern organisieren wir auch Ihren Rücktransfer von {route.name} zum Flughafen Antalya. Teilen Sie uns bei der Buchung Ihre Flugnummer und gewünschte Abholzeit mit.</p><h3>Privat statt Sammeltransfer</h3><p>Bei diesem Transfer reisen nur Sie und Ihre Mitreisenden im Fahrzeug. Nach der Reservierung erhalten Sie eine klare Bestätigung mit Reisedaten und Kontaktmöglichkeit. Am Ankunftstag verfolgt unser Team Ihren Flug; bei einer früheren oder späteren Landung stimmen wir die Übergabe entsprechend ab. Der Fahrer bringt Sie mit Gepäck direkt zur Rezeption oder zur angegebenen Privatadresse in {route.name}.</p><p>Der ausgewiesene Betrag ist ein fester Gesamtpreis für das Fahrzeug, nicht pro Person. Es gibt keine versteckten Zuschläge für die Flugüberwachung, die übliche Wartezeit oder Kindersitze auf Anfrage. Bezahlt wird bar direkt beim Fahrer, zu Beginn der Fahrt. Damit kennen Sie die Kosten schon vor der Anreise und können entspannt starten.</p><h3>Fahrzeug, Gepäck und Kinder</h3><p>Der Mercedes Vito eignet sich für bis zu sechs Personen mit normalem Reisegepäck; für größere Gruppen steht ein Mercedes Sprinter mit bis zu 12 Plätzen zur Verfügung. Teilen Sie uns Sondergepäck, einen Kinderwagen oder die benötigten Kindersitze bitte bei der Buchung mit. So planen wir Ihr Fahrzeug passend zu Ihrer Reisegruppe.</p></>}<h3>{text.included}</h3><ul>{text.items.map((item) => <li key={item}>{item}</li>)}</ul></div><aside><h2>{text.priceHeading}</h2><div className="localized-price"><p>{text.vito}</p><strong>€{route.prices.vito}</strong>{germanHotels && <span>Preis für das gesamte Fahrzeug</span>}</div><div className="localized-price"><p>{text.sprinter}</p><strong>€{route.prices.sprinter}</strong>{germanHotels && <span>Preis für das gesamte Fahrzeug</span>}</div>{germanHotels && <ul className="localized-price-trust"><li>Keine Vorauszahlung erforderlich</li><li>Zahlung direkt beim Fahrer</li><li>Keine versteckten Gebühren</li></ul>}<p><a className="button button-gold" href={`${homeHref}#booking`}>{text.book}</a></p></aside></div></section>
        {germanHotels && <section className="localized-hotels"><div><p className="eyebrow"><span />Für Ihre Unterkunft</p><h2>Beliebte Hotels in {route.name}</h2><p>Wir fahren direkt zu diesen und weiteren Hotels in der Region.</p></div><ul>{germanHotels.map((hotel) => { const catalogued = cataloguedHotels.find((entry) => entry.name === hotel); return <li key={hotel}>{catalogued ? <a href={`/de/hotels/${catalogued.slug}/`}>{hotel}</a> : hotel}</li>; })}</ul></section>}
        <section className="localized-faq"><h2>{text.faq}</h2>{germanFaq.map(([question, answer]) => <article key={question}><h3>{question}</h3><p>{answer}</p></article>)}</section>
        <section className="localized-links"><h2>{text.other}</h2><div>{publicRouteSlugs.filter((slug) => slug !== route.slug).map((slug) => <a href={`${prefix}/transfers/${slug}/`} key={slug}>{(routeCatalog[slug].names as Record<string, string>)[language] ?? routeCatalog[slug].names.en}</a>)}</div></section>
        <section className="localized-contact" id="contact"><h2>{text.book}</h2><p>{text.contact}</p><a className="button button-gold" href="https://wa.me/905302655790">WhatsApp</a></section>
      </main>
      <div hidden aria-hidden="true"><BookingForm selection={{ route: route.slug, vehicle: "vito", nonce: 1 }} scrollOnSelect={false} /></div>
      <footer><div className="footer-bottom"><span>© 2026 Antalya VIP Tourism</span><span><a href={text.imprintUrl}>{text.imprint}</a> · <a href={text.privacyUrl}>{text.privacy}</a></span></div></footer>
    </>
  );
}
