import { localizedRoute, publicRouteSlugs, routeCatalog } from "../../../src/routes.js";
import { hotelsForRegion } from "../../../src/hotels.js";
import type { IndexableLanguage } from "../lib/seo";
import { routeCopy } from "../lib/seo";
import { BookingForm } from "./BookingForm";
import { StaticPageHeader } from "./StaticPageHeader";

type LocalizedRoute = NonNullable<ReturnType<typeof localizedRoute>>;

const germanLandingHotels: Partial<Record<string, readonly string[]>> = {
  belek: ["Rixos Premium Belek", "The Land of Legends", "Maxx Royal Belek", "Regnum Carya", "Gloria Golf Resort"],
  side: ["Arum Barut Collection", "Side Star Resort", "Royal Dragon Hotel", "Barut Hemera", "Voyage Sorgun"],
  kemer: ["Maxx Royal Kemer Resort", "Akka Antedon Hotel", "Rixos Sungate", "Nirvana Mediterranean Excellence", "Crystal De Luxe Resort"],
  alanya: ["Goldcity Hotel", "Haydarpasha Palace", "Labranda Alantur", "Granada Luxury Beach", "Long Beach Resort"],
  kizilagac: ["Starlight Resort Hotel", "Sunrise Resort Hotel", "Crystal Admiral Resort", "Club Hotel Turan Prince", "Selectum Family Resort"],
  tekirova: ["Rixos Premium Tekirova", "Nirvana Dolce Vita", "Amara Dolce Vita", "Club Marco Polo", "Pirate’s Beach Club"],
};

const germanRegionCopy: Partial<Record<string, { about: string; routeDetails: string }>> = {
  belek: { about: "Belek liegt östlich von Antalya und ist besonders für Golfplätze, große All-inclusive-Resorts und breite Sandstrände bekannt. Die Hotelanlagen verteilen sich zwischen Kadriye und der Küste bei Serik; deshalb ist die genaue Hoteladresse bei der Reservierung hilfreich.", routeDetails: "Die Fahrt führt vom Flughafen Antalya über die D400 in Richtung Serik und Belek. Für Familien, Golfer und Gäste mit spätem Flug ist der direkte Privattransfer praktisch, weil Sie ohne Sammelstopps oder Umstieg direkt an Ihrer Unterkunft ankommen." },
  side: { about: "Side verbindet eine historische Altstadt mit langen Sandstränden und weitläufigen Ferienanlagen. Zum Urlaubsort gehören neben Side auch die beliebten Hotelzonen Kumköy, Evrenseki, Çolaklı, Sorgun und Titreyengöl.", routeDetails: "Vom Flughafen Antalya führt die Strecke über die Küstenstraße in Richtung Manavgat und Side. Besonders bei einer späten Ankunft ist ein privates Fahrzeug angenehm: Ihre Reisegruppe fährt direkt zum gebuchten Resort, ohne auf andere Hotelgäste zu warten." },
  kemer: { about: "Kemer liegt westlich von Antalya zwischen dem Taurusgebirge und dem Mittelmeer. Die Region umfasst Kemer Zentrum sowie Beldibi, Göynük, Kiriş und Çamyuva – Orte mit Strandhotels, Jachthafen und Bergkulisse.", routeDetails: "Die direkte Fahrt folgt der Küste westlich von Antalya. Ihr Fahrer bringt Sie ohne Umstieg zu Ihrem Hotel; das ist besonders bequem, wenn Sie mit Kindern, Sportgepäck oder nach einer Abendlandung anreisen." },
  alanya: { about: "Alanya ist eines der beliebtesten Ferienziele an der türkischen Riviera und liegt deutlich weiter östlich als die Resorts um Antalya. Neben dem Zentrum gehören Mahmutlar, Kestel, Avsallar, Türkler und Okurcalar zu den häufig angefragten Hotelgebieten.", routeDetails: "Die längere Küstenfahrt macht einen festen Fahrzeugpreis besonders transparent. Mit einem Privattransfer reisen Sie direkt mit Ihrer eigenen Gruppe und können nach der Landung entspannt bis vor die Rezeption Ihres Hotels weiterfahren." },
  kizilagac: { about: "Kızılağaç liegt östlich von Manavgat und ist für weitläufige Strandresorts und ruhige Familienferien bekannt. Die Gegend grenzt an Sorgun und Manavgat; viele Hotels liegen etwas abseits der Hauptstraße direkt am Meer.", routeDetails: "Vom Flughafen Antalya fahren Sie über die D400 in Richtung Manavgat und anschließend weiter nach Kızılağaç. Ein privates Fahrzeug erspart die zusätzlichen Hotelstopps, die bei Sammeltransfers gerade auf dieser Strecke üblich sein können." },
  tekirova: { about: "Tekirova liegt südlich von Kemer am Rand des Olympos-Beydağları-Nationalparks. Der Ort verbindet gepflegte Resortanlagen mit kleinen Buchten und liegt nahe der antiken Stätte Phaselis.", routeDetails: "Die Fahrt führt vom Flughafen Antalya über Kemer weiter nach Tekirova. Die Küstenlage und die Entfernung machen einen direkten Transfer sinnvoll: Sie fahren ohne Umstieg und ohne Wartezeit auf andere Gäste bis zu Ihrem Hotel." },
};

const copy = {
  en: {
    home: "Home", routes: "Transfer routes", priceHeading: "Fixed transfer prices", included: "Included in the price", duration: "Estimated time", distance: "Distance", from: "Price from", book: "Book your transfer", faq: "Frequently asked questions", other: "Other Antalya Airport transfers", campaign: "Online special pricing is available for all transfer routes.", contact: "Contact us on WhatsApp for bookings and questions.", privacy: "Privacy", imprint: "Imprint", privacyUrl: "/privacy/", imprintUrl: "/impressum.html", vito: "Mercedes Vito · up to 7 passengers", sprinter: "Mercedes Sprinter · up to 13 passengers", intro: (name: string, duration: string, distance: string) => `The ${distance} journey from Antalya Airport to ${name} takes approximately ${duration} in normal traffic. Your chauffeur meets you in arrivals with a name sign and drives directly to your accommodation.`, items: ["Personal meet and greet", "Real-time flight tracking", "Airport parking and waiting", "Luggage assistance and bottled water", "Free child seat on request"], faqItems: (name: string, price: number, duration: string) => [[`How long is the transfer from Antalya Airport to ${name}?`, `The journey takes approximately ${duration} in normal traffic.`], [`What is the fixed transfer price to ${name}?`, `Mercedes Vito prices start from €${price} per vehicle. The confirmed total is shown when booking.`], ["What happens if my flight is delayed?", "We track your flight in real time and adjust the meeting time at no extra charge."]],
  },
  de: {
    home: "Startseite", routes: "Transferrouten", priceHeading: "Feste Transferpreise", included: "Im Preis enthalten", duration: "Geschätzte Fahrzeit", distance: "Entfernung", from: "Preis ab", book: "Transfer buchen", faq: "Häufig gestellte Fragen", other: "Weitere Transfers vom Flughafen Antalya", campaign: "Online-Spezialpreise sind für alle Transferstrecken verfügbar.", contact: "Für Buchungen und Fragen erreichen Sie uns über WhatsApp.", privacy: "Datenschutz", imprint: "Impressum", privacyUrl: "/de/datenschutz/", imprintUrl: "/de/impressum/", vito: "Mercedes Vito · bis 7 Personen", sprinter: "Mercedes Sprinter · bis 13 Personen", intro: (name: string, duration: string, distance: string) => `Die ${distance} lange Fahrt vom Flughafen Antalya nach ${name} dauert bei normalem Verkehr ungefähr ${duration}. Nachdem Sie Ihr Gepäck abgeholt haben, gehen Sie bitte zum Meet & Greet Bereich J / 777. Unser Flughafen-Team findet Ihre Buchung und bringt Sie mit Ihrem Fahrer zusammen; anschließend fahren Sie direkt zu Ihrer Unterkunft.`, items: ["Persönlicher Empfang mit Namensschild", "Flugverfolgung in Echtzeit", "Flughafenparken und Wartezeit", "Gepäckhilfe und Mineralwasser", "Kostenloser Kindersitz auf Wunsch"], faqItems: (name: string, price: number, duration: string) => [[`Wie lange dauert der Transfer vom Flughafen Antalya nach ${name}?`, `Die Fahrt dauert bei normalem Verkehr ungefähr ${duration}.`], [`Was kostet der Festpreis-Transfer nach ${name}?`, `Die Preise für einen Mercedes Vito beginnen bei €${price} pro Fahrzeug. Der bestätigte Gesamtpreis wird bei der Buchung angezeigt.`], ["Was passiert bei einer Flugverspätung?", "Wir verfolgen Ihren Flug in Echtzeit und passen die Abholzeit ohne Aufpreis an."]],
  },
  tr: {
    home: "Ana sayfa", routes: "Transfer rotaları", priceHeading: "Sabit transfer fiyatları", included: "Fiyata dahil olanlar", duration: "Tahmini süre", distance: "Mesafe", from: "Başlangıç fiyatı", book: "Transferinizi ayırtın", faq: "Sık sorulan sorular", other: "Diğer Antalya Havalimanı transferleri", campaign: "Online'a özel fiyatlar tüm transfer rotalarında sunulmaktadır.", contact: "Rezervasyon ve sorularınız için WhatsApp üzerinden bize ulaşın.", privacy: "Gizlilik", imprint: "Künye", privacyUrl: "/tr/gizlilik/", imprintUrl: "/tr/kunye/", vito: "Mercedes Vito · 7 yolcuya kadar", sprinter: "Mercedes Sprinter · 13 yolcuya kadar", intro: (name: string, duration: string, distance: string) => `Antalya Havalimanı ile ${name} arasındaki ${distance} mesafeli yolculuk normal trafik koşullarında yaklaşık ${duration} sürer. Şoförünüz sizi gelen yolcu salonunda isim tabelasıyla karşılar ve doğrudan konaklama adresinize götürür.`, items: ["Kişisel isim tabelasıyla karşılama", "Gerçek zamanlı uçuş takibi", "Havalimanı otoparkı ve bekleme", "Bagaj yardımı ve şişe su", "Talep üzerine ücretsiz çocuk koltuğu"], faqItems: (name: string, price: number, duration: string) => [[`Antalya Havalimanı ile ${name} arası transfer ne kadar sürer?`, `Normal trafik koşullarında yolculuk yaklaşık ${duration} sürer. Trafik ve otel konumu süreyi etkileyebilir.`], [`${name} transferinin sabit fiyatı nedir?`, `Mercedes Vito fiyatları araç başına €${price}'dan başlar. Kesin toplam rezervasyon sırasında gösterilir.`], ["Uçuşum gecikirse ne olur?", "Uçuşunuzu gerçek zamanlı takip eder, karşılama saatini ücretsiz olarak güncelleriz."]],
  },
  ru: {
    home: "Главная", routes: "Маршруты трансфера", priceHeading: "Фиксированные цены", included: "В стоимость включено", duration: "Время в пути", distance: "Расстояние", from: "Цена от", book: "Забронировать трансфер", faq: "Частые вопросы", other: "Другие трансферы из аэропорта Антальи", campaign: "Специальные онлайн-тарифы доступны для всех маршрутов трансфера.", contact: "Для бронирования и вопросов напишите нам в WhatsApp.", privacy: "Конфиденциальность", imprint: "Правовая информация", privacyUrl: "/ru/privacy/", imprintUrl: "/ru/impressum/", vito: "Mercedes Vito · до 7 пассажиров", sprinter: "Mercedes Sprinter · до 13 пассажиров", intro: (name: string, duration: string, distance: string) => `Поездка из аэропорта Антальи в ${name} на расстояние ${distance} занимает примерно ${duration} при обычном движении. Водитель встретит вас в зале прилёта с именной табличкой и отвезёт прямо к месту проживания.`, items: ["Встреча с именной табличкой", "Отслеживание рейса в реальном времени", "Парковка и ожидание в аэропорту", "Помощь с багажом и вода", "Бесплатное детское кресло по запросу"], faqItems: (name: string, price: number, duration: string) => [[`Сколько длится трансфер из аэропорта Антальи в ${name}?`, `При обычном движении поездка занимает около ${duration}. Точное время зависит от дорожной ситуации и расположения отеля.`], [`Сколько стоит трансфер в ${name}?`, `Стоимость Mercedes Vito начинается от €${price} за автомобиль. Итоговая фиксированная цена показывается при бронировании.`], ["Что произойдёт при задержке рейса?", "Мы отслеживаем рейс в реальном времени и бесплатно корректируем время встречи."]],
  },
  fr: {
    home: "Accueil", routes: "Routes de transfert", priceHeading: "Prix fixes de transfert", included: "Inclus dans le prix", duration: "Durée estimée", distance: "Distance", from: "Prix à partir de", book: "Réserver votre transfert", faq: "Questions fréquentes", other: "Autres transferts depuis l'aéroport d'Antalya", campaign: "Des tarifs spéciaux en ligne sont disponibles pour toutes les routes de transfert.", contact: "Contactez-nous sur WhatsApp pour les réservations et questions.", privacy: "Confidentialité", imprint: "Mentions légales", privacyUrl: "/fr/privacy/", imprintUrl: "/fr/impressum/", vito: "Mercedes Vito · jusqu'à 7 passagers", sprinter: "Mercedes Sprinter · jusqu'à 13 passagers", intro: (name: string, duration: string, distance: string) => `Le trajet de ${distance} depuis l'aéroport d'Antalya jusqu'à ${name} dure environ ${duration} en trafic normal. Après avoir récupéré vos bagages, rendez-vous dans la zone Meet & Greet J / 777. Notre équipe identifiera votre réservation et vous mettra en contact avec votre chauffeur.`, items: ["Accueil personnalisé avec pancarte nominative", "Suivi du vol en temps réel", "Parking aéroport et attente inclus", "Aide aux bagages et eau en bouteille", "Siège enfant gratuit sur demande"], faqItems: (name: string, price: number, duration: string) => [[`Combien de temps dure le transfert de l'aéroport d'Antalya vers ${name} ?`, `Le trajet dure environ ${duration} en trafic normal.`], [`Quel est le prix fixe du transfert vers ${name} ?`, `Les prix Mercedes Vito commencent à €${price} par véhicule. Le montant total confirmé est affiché lors de la réservation.`], ["Que se passe-t-il si mon vol est retardé ?", "Nous suivons votre vol en temps réel et ajustons l'heure de prise en charge sans frais supplémentaires."]],
  },
  cs: {
    home: "Domů", routes: "Trasy transferů", priceHeading: "Pevné ceny transferů", included: "Co je zahrnuto v ceně", duration: "Odhadovaný čas", distance: "Vzdálenost", from: "Cena od", book: "Rezervovat transfer", faq: "Často kladené dotazy", other: "Další transfery z letiště Antalya", campaign: "Speciální online ceny jsou dostupné pro všechny transferové trasy.", contact: "Pro rezervace a dotazy nás kontaktujte na WhatsApp.", privacy: "Ochrana soukromí", imprint: "Impressum", privacyUrl: "/cs/privacy/", imprintUrl: "/cs/impressum/", vito: "Mercedes Vito · až 7 cestujících", sprinter: "Mercedes Sprinter · až 13 cestujících", intro: (name: string, duration: string, distance: string) => `Cesta z letiště Antalya do ${name}, vzdálená ${distance}, trvá přibližně ${duration} při běžném provozu. Váš šofér vás uvítá v příletové hale s jmenovkou a odveze vás přímo do ubytování.`, items: ["Osobní uvítání se jmenovkou", "Sledování letů v reálném čase", "Parkoviště na letišti a čekání", "Pomoc se zavazadly a balená voda", "Bezplatná dětská sedačka na vyžádání"], faqItems: (name: string, price: number, duration: string) => [[`Jak dlouho trvá transfer z letiště Antalya do ${name}?`, `Cesta trvá přibližně ${duration} při běžném provozu.`], [`Jaká je pevná cena transferu do ${name}?`, `Ceny Mercedes Vito začínají od €${price} za vozidlo. Potvrzená celková cena je zobrazena při rezervaci.`], ["Co se stane, když má můj let zpoždění?", "Sledujeme váš let v reálném čase a upravujeme čas setkání bez příplatku."]],
  },
} as const;

export function TransferPage({ language, route }: { language: IndexableLanguage; route: LocalizedRoute }) {
  const text = copy[language];
  const seo = routeCopy(language);
  const prefix = language === "en" ? "" : `/${language}`;
  const homeHref = `${prefix}/`;
  const heading = seo.heading(route.name);
  const faq = text.faqItems(route.name, route.prices.vito, route.durationLabel);
  const germanHotels = language === "de" ? germanLandingHotels[route.slug] : undefined;
  const cataloguedHotels = language === "de" ? hotelsForRegion(route.slug) : [];
  const germanRegion = language === "de" ? germanRegionCopy[route.slug] : undefined;
  const germanFaq = germanHotels ? [
    ...faq,
    ["Wo treffe ich das Transfer-Team am Flughafen Antalya?", "Nachdem Sie Ihr Gepäck abgeholt haben, gehen Sie bitte zum Meet & Greet Bereich J / 777. Unser Flughafen-Team findet Ihre Buchung und bringt Sie mit Ihrem Fahrer zusammen."],
    ["Muss ich den Transfer im Voraus bezahlen?", "Nein. Eine Vorauszahlung ist nicht erforderlich. Sie zahlen den festen Gesamtpreis direkt beim Fahrer."],
    ["Ist ein Kindersitz verfügbar?", "Ja. Kindersitze stellen wir auf Wunsch kostenlos bereit. Bitte geben Sie Alter und Anzahl der Kinder bei der Buchung an."],
  ] : faq;

  return (
    <>
      <StaticPageHeader homeHref={homeHref} homeLabel={text.home} secondaryHref="#details" secondaryLabel={text.routes} tertiaryHref="#contact" tertiaryLabel="WhatsApp" ctaHref={`${homeHref}#booking`} ctaLabel={text.book} />
      <main>
        <section className="localized-route"><div className="eyebrow light"><span /><p>Antalya VIP Tourism</p></div><h1>{germanHotels ? `Flughafen Antalya → ${route.name} Privattransfer` : heading}</h1><p>{seo.description(route.name, route.prices.vito)}</p>{germanHotels ? <><a className="button button-gold" href={`${homeHref}#booking`}>Jetzt Transfer buchen</a><ul className="localized-trust"><li>Bis zu 7 Personen</li><li>Keine Vorauszahlung erforderlich</li><li>Zahlung direkt beim Fahrer</li><li>Fester Gesamtpreis ohne versteckte Gebühren</li><li>Kostenloser Kindersitz auf Anfrage</li><li>Flugüberwachung inklusive</li></ul></> : <p className="localized-campaign">{text.campaign}</p>}<div className="localized-stats"><div><strong>{route.durationLabel}</strong><span>{text.duration}</span></div><div><strong>{route.distance}</strong><span>{text.distance}</span></div><div><strong>€{route.prices.vito}</strong><span>{text.from}</span></div></div></section>
        <section className="localized-content" id="details"><div className="localized-grid"><div><h2>{germanHotels ? `Ihr privater Transfer nach ${route.name}` : heading}</h2><p>{text.intro(route.name, route.durationLabel, route.distance)}</p>{germanRegion && <><h3>Über {route.name}</h3><p>{germanRegion.about}</p><p>{germanRegion.routeDetails}</p></>}{germanHotels && <><p>Sie reisen ausschließlich mit Ihrer eigenen Gruppe direkt zu Ihrem Hotel in {route.name}. Kein Shuttle, keine fremden Fahrgäste und keine unnötigen Zwischenstopps – der feste Preis gilt für das gesamte Fahrzeug.</p><h3>Ihre Ankunft am Flughafen Antalya</h3><p>Nachdem Sie Ihr Gepäck abgeholt haben, gehen Sie bitte zum Meet & Greet Bereich J / 777. Unser Flughafen-Team findet Ihre Buchung und bringt Sie mit Ihrem Fahrer zusammen. Dank Flugüberwachung passen wir die Abholung bei einer Verspätung ohne Aufpreis an.</p><h3>Hin- und Rücktransfer</h3><p>Gern organisieren wir auch Ihren Rücktransfer von {route.name} zum Flughafen Antalya. Teilen Sie uns bei der Buchung Ihre Flugnummer und gewünschte Abholzeit mit.</p><h3>Privat statt Sammeltransfer</h3><p>Bei diesem Transfer reisen nur Sie und Ihre Mitreisenden im Fahrzeug. Nach der Reservierung erhalten Sie eine klare Bestätigung mit Reisedaten und Kontaktmöglichkeit. Am Ankunftstag verfolgt unser Team Ihren Flug; bei einer früheren oder späteren Landung stimmen wir die Übergabe entsprechend ab. Der Fahrer bringt Sie mit Gepäck direkt zur Rezeption oder zur angegebenen Privatadresse in {route.name}.</p><p>Der ausgewiesene Betrag ist ein fester Gesamtpreis für das Fahrzeug, nicht pro Person. Es gibt keine versteckten Zuschläge für die Flugüberwachung, die übliche Wartezeit oder Kindersitze auf Anfrage. Bezahlt wird erst direkt beim Fahrer. Damit kennen Sie die Kosten schon vor der Anreise und können entspannt starten.</p><h3>Fahrzeug, Gepäck und Kinder</h3><p>Der Mercedes Vito eignet sich für bis zu sieben Personen mit normalem Reisegepäck; für größere Gruppen steht ein Mercedes Sprinter mit bis zu 13 Plätzen zur Verfügung. Teilen Sie uns Sondergepäck, einen Kinderwagen oder die benötigten Kindersitze bitte bei der Buchung mit. So planen wir Ihr Fahrzeug passend zu Ihrer Reisegruppe.</p></>}<h3>{text.included}</h3><ul>{text.items.map((item) => <li key={item}>{item}</li>)}</ul></div><aside><h2>{text.priceHeading}</h2><div className="localized-price"><p>{text.vito}</p><strong>€{route.prices.vito}</strong>{germanHotels && <span>Preis für das gesamte Fahrzeug</span>}</div><div className="localized-price"><p>{text.sprinter}</p><strong>€{route.prices.sprinter}</strong>{germanHotels && <span>Preis für das gesamte Fahrzeug</span>}</div>{germanHotels && <ul className="localized-price-trust"><li>Keine Vorauszahlung erforderlich</li><li>Zahlung direkt beim Fahrer</li><li>Keine versteckten Gebühren</li></ul>}<p><a className="button button-gold" href={`${homeHref}#booking`}>{text.book}</a></p></aside></div></section>
        {germanHotels && <section className="localized-hotels"><div><p className="eyebrow"><span />Für Ihre Unterkunft</p><h2>Beliebte Hotels in {route.name}</h2><p>Wir fahren direkt zu diesen und weiteren Hotels in der Region.</p></div><ul>{germanHotels.map((hotel) => { const catalogued = cataloguedHotels.find((entry) => entry.name === hotel); return <li key={hotel}>{catalogued ? <a href={`/de/hotels/${catalogued.slug}/`}>{hotel}</a> : hotel}</li>; })}</ul></section>}
        <section className="localized-faq"><h2>{text.faq}</h2>{germanFaq.map(([question, answer]) => <article key={question}><h3>{question}</h3><p>{answer}</p></article>)}</section>
        <section className="localized-links"><h2>{text.other}</h2><div>{publicRouteSlugs.filter((slug) => slug !== route.slug).map((slug) => <a href={`${prefix}/transfers/${slug}/`} key={slug}>{(routeCatalog[slug].names as Record<string, string>)[language] ?? routeCatalog[slug].names.en}</a>)}</div></section>
        <section className="localized-contact" id="contact"><h2>{text.book}</h2><p>{text.contact}</p><a className="button button-gold" href="https://wa.me/905302655790">WhatsApp</a></section>
      </main>
      <div hidden aria-hidden="true"><BookingForm selection={{ route: route.slug, vehicle: "vito", nonce: 1 }} scrollOnSelect={false} /></div>
      <footer><div className="footer-bottom"><span>© 2026 Antalya VIP Tourism</span><span><a href={text.imprintUrl}>{text.imprint}</a> · <a href={text.privacyUrl}>{text.privacy}</a></span></div></footer>
    </>
  );
}
