// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/de": {
    params: {};
  };
  "/tr": {
    params: {};
  };
  "/ru": {
    params: {};
  };
  "/transfers/:slug": {
    params: {
      "slug": string;
    };
  };
  "/:language/transfers/:slug": {
    params: {
      "language": string;
      "slug": string;
    };
  };
  "/impressum.html": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/de/datenschutz": {
    params: {};
  };
  "/de/impressum": {
    params: {};
  };
  "/tr/gizlilik": {
    params: {};
  };
  "/tr/kunye": {
    params: {};
  };
  "/ru/privacy": {
    params: {};
  };
  "/ru/impressum": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/de" | "/tr" | "/ru" | "/transfers/:slug" | "/:language/transfers/:slug" | "/impressum.html" | "/privacy" | "/de/datenschutz" | "/de/impressum" | "/tr/gizlilik" | "/tr/kunye" | "/ru/privacy" | "/ru/impressum";
  };
  "./routes/home.tsx": {
    id: "home-en";
    page: "/";
  } | {
    id: "home-de";
    page: "/de";
  } | {
    id: "home-tr";
    page: "/tr";
  } | {
    id: "home-ru";
    page: "/ru";
  };
  "./routes/transfer.tsx": {
    id: "transfer-en";
    page: "/transfers/:slug";
  } | {
    id: "transfer-localized";
    page: "/:language/transfers/:slug";
  };
  "./routes/legal.tsx": {
    id: "legal-imprint-en";
    page: "/impressum.html";
  } | {
    id: "legal-privacy-en";
    page: "/privacy";
  } | {
    id: "legal-privacy-de";
    page: "/de/datenschutz";
  } | {
    id: "legal-imprint-de";
    page: "/de/impressum";
  } | {
    id: "legal-privacy-tr";
    page: "/tr/gizlilik";
  } | {
    id: "legal-imprint-tr";
    page: "/tr/kunye";
  } | {
    id: "legal-privacy-ru";
    page: "/ru/privacy";
  } | {
    id: "legal-imprint-ru";
    page: "/ru/impressum";
  };
};

type RouteModules = {
  "root": typeof import("./public-app/app/root.tsx");
  "home-en": typeof import("./public-app/app/./routes/home.tsx");
  "home-de": typeof import("./public-app/app/./routes/home.tsx");
  "home-tr": typeof import("./public-app/app/./routes/home.tsx");
  "home-ru": typeof import("./public-app/app/./routes/home.tsx");
  "transfer-en": typeof import("./public-app/app/./routes/transfer.tsx");
  "transfer-localized": typeof import("./public-app/app/./routes/transfer.tsx");
  "legal-imprint-en": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-privacy-en": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-privacy-de": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-imprint-de": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-privacy-tr": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-imprint-tr": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-privacy-ru": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-imprint-ru": typeof import("./public-app/app/./routes/legal.tsx");
};