// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/de": {
    params: {};
  };
  "/fr": {
    params: {};
  };
  "/tr": {
    params: {};
  };
  "/ru": {
    params: {};
  };
  "/cs": {
    params: {};
  };
  "/uk": {
    params: {};
  };
  "/ur": {
    params: {};
  };
  "/pl": {
    params: {};
  };
  "/nl": {
    params: {};
  };
  "/ar": {
    params: {};
  };
  "/sv": {
    params: {};
  };
  "/da": {
    params: {};
  };
  "/el": {
    params: {};
  };
  "/es": {
    params: {};
  };
  "/he": {
    params: {};
  };
  "/hu": {
    params: {};
  };
  "/it": {
    params: {};
  };
  "/ja": {
    params: {};
  };
  "/ko": {
    params: {};
  };
  "/pt": {
    params: {};
  };
  "/ro": {
    params: {};
  };
  "/zh": {
    params: {};
  };
  "/health": {
    params: {};
  };
  "/de/health": {
    params: {};
  };
  "/fr/health": {
    params: {};
  };
  "/tr/health": {
    params: {};
  };
  "/ru/health": {
    params: {};
  };
  "/cs/health": {
    params: {};
  };
  "/uk/health": {
    params: {};
  };
  "/ur/health": {
    params: {};
  };
  "/pl/health": {
    params: {};
  };
  "/nl/health": {
    params: {};
  };
  "/ar/health": {
    params: {};
  };
  "/sv/health": {
    params: {};
  };
  "/da/health": {
    params: {};
  };
  "/el/health": {
    params: {};
  };
  "/es/health": {
    params: {};
  };
  "/he/health": {
    params: {};
  };
  "/hu/health": {
    params: {};
  };
  "/it/health": {
    params: {};
  };
  "/ja/health": {
    params: {};
  };
  "/ko/health": {
    params: {};
  };
  "/pt/health": {
    params: {};
  };
  "/ro/health": {
    params: {};
  };
  "/zh/health": {
    params: {};
  };
  "/clinic": {
    params: {};
  };
  "/transfers/:slug": {
    params: {
      "slug": string;
    };
  };
  "/:language/transfers/:slug": {
    params: {
      "language": string;
      "slug": string;
    };
  };
  "/de/hotels/:hotelSlug": {
    params: {
      "hotelSlug": string;
    };
  };
  "/impressum.html": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/de/datenschutz": {
    params: {};
  };
  "/de/impressum": {
    params: {};
  };
  "/tr/gizlilik": {
    params: {};
  };
  "/tr/kunye": {
    params: {};
  };
  "/ru/privacy": {
    params: {};
  };
  "/ru/impressum": {
    params: {};
  };
  "/cs/privacy": {
    params: {};
  };
  "/cs/impressum": {
    params: {};
  };
  "/uk/privacy": {
    params: {};
  };
  "/uk/impressum": {
    params: {};
  };
  "/ur/privacy": {
    params: {};
  };
  "/ur/impressum": {
    params: {};
  };
  "/ru/blog": {
    params: {};
  };
  "/de/blog": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/pl/blog": {
    params: {};
  };
  "/uk/blog": {
    params: {};
  };
  "/nl/blog": {
    params: {};
  };
  "/cs/blog": {
    params: {};
  };
  "/ro/blog": {
    params: {};
  };
  "/tr/blog": {
    params: {};
  };
  "/he/blog": {
    params: {};
  };
  "/fr/blog": {
    params: {};
  };
  "/sv/blog": {
    params: {};
  };
  "/da/blog": {
    params: {};
  };
  "/ar/blog": {
    params: {};
  };
  "/hu/blog": {
    params: {};
  };
  "/es/blog": {
    params: {};
  };
  "/it/blog": {
    params: {};
  };
  "/pt/blog": {
    params: {};
  };
  "/el/blog": {
    params: {};
  };
  "/zh/blog": {
    params: {};
  };
  "/ko/blog": {
    params: {};
  };
  "/ja/blog": {
    params: {};
  };
  "/ur/blog": {
    params: {};
  };
  "/ru/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/de/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/pl/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/uk/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/nl/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/cs/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/ro/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/tr/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/he/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/fr/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/sv/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/da/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/ar/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/hu/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/es/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/it/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/pt/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/el/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/zh/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/ko/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/ja/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/ur/blog/:slug": {
    params: {
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/de" | "/fr" | "/tr" | "/ru" | "/cs" | "/uk" | "/ur" | "/pl" | "/nl" | "/ar" | "/sv" | "/da" | "/el" | "/es" | "/he" | "/hu" | "/it" | "/ja" | "/ko" | "/pt" | "/ro" | "/zh" | "/health" | "/de/health" | "/fr/health" | "/tr/health" | "/ru/health" | "/cs/health" | "/uk/health" | "/ur/health" | "/pl/health" | "/nl/health" | "/ar/health" | "/sv/health" | "/da/health" | "/el/health" | "/es/health" | "/he/health" | "/hu/health" | "/it/health" | "/ja/health" | "/ko/health" | "/pt/health" | "/ro/health" | "/zh/health" | "/clinic" | "/transfers/:slug" | "/:language/transfers/:slug" | "/de/hotels/:hotelSlug" | "/impressum.html" | "/privacy" | "/de/datenschutz" | "/de/impressum" | "/tr/gizlilik" | "/tr/kunye" | "/ru/privacy" | "/ru/impressum" | "/cs/privacy" | "/cs/impressum" | "/uk/privacy" | "/uk/impressum" | "/ur/privacy" | "/ur/impressum" | "/ru/blog" | "/de/blog" | "/blog" | "/pl/blog" | "/uk/blog" | "/nl/blog" | "/cs/blog" | "/ro/blog" | "/tr/blog" | "/he/blog" | "/fr/blog" | "/sv/blog" | "/da/blog" | "/ar/blog" | "/hu/blog" | "/es/blog" | "/it/blog" | "/pt/blog" | "/el/blog" | "/zh/blog" | "/ko/blog" | "/ja/blog" | "/ur/blog" | "/ru/blog/:slug" | "/de/blog/:slug" | "/blog/:slug" | "/pl/blog/:slug" | "/uk/blog/:slug" | "/nl/blog/:slug" | "/cs/blog/:slug" | "/ro/blog/:slug" | "/tr/blog/:slug" | "/he/blog/:slug" | "/fr/blog/:slug" | "/sv/blog/:slug" | "/da/blog/:slug" | "/ar/blog/:slug" | "/hu/blog/:slug" | "/es/blog/:slug" | "/it/blog/:slug" | "/pt/blog/:slug" | "/el/blog/:slug" | "/zh/blog/:slug" | "/ko/blog/:slug" | "/ja/blog/:slug" | "/ur/blog/:slug";
  };
  "./routes/home.tsx": {
    id: "home-en";
    page: "/";
  } | {
    id: "home-de";
    page: "/de";
  } | {
    id: "home-fr";
    page: "/fr";
  } | {
    id: "home-tr";
    page: "/tr";
  } | {
    id: "home-ru";
    page: "/ru";
  } | {
    id: "home-cs";
    page: "/cs";
  } | {
    id: "home-uk";
    page: "/uk";
  } | {
    id: "home-ur";
    page: "/ur";
  } | {
    id: "home-pl";
    page: "/pl";
  } | {
    id: "home-nl";
    page: "/nl";
  } | {
    id: "home-ar";
    page: "/ar";
  } | {
    id: "home-sv";
    page: "/sv";
  } | {
    id: "home-da";
    page: "/da";
  } | {
    id: "home-el";
    page: "/el";
  } | {
    id: "home-es";
    page: "/es";
  } | {
    id: "home-he";
    page: "/he";
  } | {
    id: "home-hu";
    page: "/hu";
  } | {
    id: "home-it";
    page: "/it";
  } | {
    id: "home-ja";
    page: "/ja";
  } | {
    id: "home-ko";
    page: "/ko";
  } | {
    id: "home-pt";
    page: "/pt";
  } | {
    id: "home-ro";
    page: "/ro";
  } | {
    id: "home-zh";
    page: "/zh";
  };
  "./routes/health.tsx": {
    id: "health-en";
    page: "/health";
  } | {
    id: "health-de";
    page: "/de/health";
  } | {
    id: "health-fr";
    page: "/fr/health";
  } | {
    id: "health-tr";
    page: "/tr/health";
  } | {
    id: "health-ru";
    page: "/ru/health";
  } | {
    id: "health-cs";
    page: "/cs/health";
  } | {
    id: "health-uk";
    page: "/uk/health";
  } | {
    id: "health-ur";
    page: "/ur/health";
  } | {
    id: "health-pl";
    page: "/pl/health";
  } | {
    id: "health-nl";
    page: "/nl/health";
  } | {
    id: "health-ar";
    page: "/ar/health";
  } | {
    id: "health-sv";
    page: "/sv/health";
  } | {
    id: "health-da";
    page: "/da/health";
  } | {
    id: "health-el";
    page: "/el/health";
  } | {
    id: "health-es";
    page: "/es/health";
  } | {
    id: "health-he";
    page: "/he/health";
  } | {
    id: "health-hu";
    page: "/hu/health";
  } | {
    id: "health-it";
    page: "/it/health";
  } | {
    id: "health-ja";
    page: "/ja/health";
  } | {
    id: "health-ko";
    page: "/ko/health";
  } | {
    id: "health-pt";
    page: "/pt/health";
  } | {
    id: "health-ro";
    page: "/ro/health";
  } | {
    id: "health-zh";
    page: "/zh/health";
  };
  "./routes/clinic.tsx": {
    id: "clinic-tr";
    page: "/clinic";
  };
  "./routes/transfer.tsx": {
    id: "transfer-en";
    page: "/transfers/:slug";
  } | {
    id: "transfer-localized";
    page: "/:language/transfers/:slug";
  };
  "./routes/hotel.tsx": {
    id: "hotel-de";
    page: "/de/hotels/:hotelSlug";
  };
  "./routes/legal.tsx": {
    id: "legal-imprint-en";
    page: "/impressum.html";
  } | {
    id: "legal-privacy-en";
    page: "/privacy";
  } | {
    id: "legal-privacy-de";
    page: "/de/datenschutz";
  } | {
    id: "legal-imprint-de";
    page: "/de/impressum";
  } | {
    id: "legal-privacy-tr";
    page: "/tr/gizlilik";
  } | {
    id: "legal-imprint-tr";
    page: "/tr/kunye";
  } | {
    id: "legal-privacy-ru";
    page: "/ru/privacy";
  } | {
    id: "legal-imprint-ru";
    page: "/ru/impressum";
  } | {
    id: "legal-privacy-cs";
    page: "/cs/privacy";
  } | {
    id: "legal-imprint-cs";
    page: "/cs/impressum";
  } | {
    id: "legal-privacy-uk";
    page: "/uk/privacy";
  } | {
    id: "legal-imprint-uk";
    page: "/uk/impressum";
  } | {
    id: "legal-privacy-ur";
    page: "/ur/privacy";
  } | {
    id: "legal-imprint-ur";
    page: "/ur/impressum";
  };
  "./routes/blog.tsx": {
    id: "blog-ru";
    page: "/ru/blog";
  } | {
    id: "blog-de";
    page: "/de/blog";
  } | {
    id: "blog-en";
    page: "/blog";
  } | {
    id: "blog-pl";
    page: "/pl/blog";
  } | {
    id: "blog-uk";
    page: "/uk/blog";
  } | {
    id: "blog-nl";
    page: "/nl/blog";
  } | {
    id: "blog-cs";
    page: "/cs/blog";
  } | {
    id: "blog-ro";
    page: "/ro/blog";
  } | {
    id: "blog-tr";
    page: "/tr/blog";
  } | {
    id: "blog-he";
    page: "/he/blog";
  } | {
    id: "blog-fr";
    page: "/fr/blog";
  } | {
    id: "blog-sv";
    page: "/sv/blog";
  } | {
    id: "blog-da";
    page: "/da/blog";
  } | {
    id: "blog-ar";
    page: "/ar/blog";
  } | {
    id: "blog-hu";
    page: "/hu/blog";
  } | {
    id: "blog-es";
    page: "/es/blog";
  } | {
    id: "blog-it";
    page: "/it/blog";
  } | {
    id: "blog-pt";
    page: "/pt/blog";
  } | {
    id: "blog-el";
    page: "/el/blog";
  } | {
    id: "blog-zh";
    page: "/zh/blog";
  } | {
    id: "blog-ko";
    page: "/ko/blog";
  } | {
    id: "blog-ja";
    page: "/ja/blog";
  } | {
    id: "blog-ur";
    page: "/ur/blog";
  };
  "./routes/article.tsx": {
    id: "article-ru";
    page: "/ru/blog/:slug";
  } | {
    id: "article-de";
    page: "/de/blog/:slug";
  } | {
    id: "article-en";
    page: "/blog/:slug";
  } | {
    id: "article-pl";
    page: "/pl/blog/:slug";
  } | {
    id: "article-uk";
    page: "/uk/blog/:slug";
  } | {
    id: "article-nl";
    page: "/nl/blog/:slug";
  } | {
    id: "article-cs";
    page: "/cs/blog/:slug";
  } | {
    id: "article-ro";
    page: "/ro/blog/:slug";
  } | {
    id: "article-tr";
    page: "/tr/blog/:slug";
  } | {
    id: "article-he";
    page: "/he/blog/:slug";
  } | {
    id: "article-fr";
    page: "/fr/blog/:slug";
  } | {
    id: "article-sv";
    page: "/sv/blog/:slug";
  } | {
    id: "article-da";
    page: "/da/blog/:slug";
  } | {
    id: "article-ar";
    page: "/ar/blog/:slug";
  } | {
    id: "article-hu";
    page: "/hu/blog/:slug";
  } | {
    id: "article-es";
    page: "/es/blog/:slug";
  } | {
    id: "article-it";
    page: "/it/blog/:slug";
  } | {
    id: "article-pt";
    page: "/pt/blog/:slug";
  } | {
    id: "article-el";
    page: "/el/blog/:slug";
  } | {
    id: "article-zh";
    page: "/zh/blog/:slug";
  } | {
    id: "article-ko";
    page: "/ko/blog/:slug";
  } | {
    id: "article-ja";
    page: "/ja/blog/:slug";
  } | {
    id: "article-ur";
    page: "/ur/blog/:slug";
  };
};

type RouteModules = {
  "root": typeof import("./public-app/app/root.tsx");
  "home-en": typeof import("./public-app/app/./routes/home.tsx");
  "home-de": typeof import("./public-app/app/./routes/home.tsx");
  "home-fr": typeof import("./public-app/app/./routes/home.tsx");
  "home-tr": typeof import("./public-app/app/./routes/home.tsx");
  "home-ru": typeof import("./public-app/app/./routes/home.tsx");
  "home-cs": typeof import("./public-app/app/./routes/home.tsx");
  "home-uk": typeof import("./public-app/app/./routes/home.tsx");
  "home-ur": typeof import("./public-app/app/./routes/home.tsx");
  "home-pl": typeof import("./public-app/app/./routes/home.tsx");
  "home-nl": typeof import("./public-app/app/./routes/home.tsx");
  "home-ar": typeof import("./public-app/app/./routes/home.tsx");
  "home-sv": typeof import("./public-app/app/./routes/home.tsx");
  "home-da": typeof import("./public-app/app/./routes/home.tsx");
  "home-el": typeof import("./public-app/app/./routes/home.tsx");
  "home-es": typeof import("./public-app/app/./routes/home.tsx");
  "home-he": typeof import("./public-app/app/./routes/home.tsx");
  "home-hu": typeof import("./public-app/app/./routes/home.tsx");
  "home-it": typeof import("./public-app/app/./routes/home.tsx");
  "home-ja": typeof import("./public-app/app/./routes/home.tsx");
  "home-ko": typeof import("./public-app/app/./routes/home.tsx");
  "home-pt": typeof import("./public-app/app/./routes/home.tsx");
  "home-ro": typeof import("./public-app/app/./routes/home.tsx");
  "home-zh": typeof import("./public-app/app/./routes/home.tsx");
  "health-en": typeof import("./public-app/app/./routes/health.tsx");
  "health-de": typeof import("./public-app/app/./routes/health.tsx");
  "health-fr": typeof import("./public-app/app/./routes/health.tsx");
  "health-tr": typeof import("./public-app/app/./routes/health.tsx");
  "health-ru": typeof import("./public-app/app/./routes/health.tsx");
  "health-cs": typeof import("./public-app/app/./routes/health.tsx");
  "health-uk": typeof import("./public-app/app/./routes/health.tsx");
  "health-ur": typeof import("./public-app/app/./routes/health.tsx");
  "health-pl": typeof import("./public-app/app/./routes/health.tsx");
  "health-nl": typeof import("./public-app/app/./routes/health.tsx");
  "health-ar": typeof import("./public-app/app/./routes/health.tsx");
  "health-sv": typeof import("./public-app/app/./routes/health.tsx");
  "health-da": typeof import("./public-app/app/./routes/health.tsx");
  "health-el": typeof import("./public-app/app/./routes/health.tsx");
  "health-es": typeof import("./public-app/app/./routes/health.tsx");
  "health-he": typeof import("./public-app/app/./routes/health.tsx");
  "health-hu": typeof import("./public-app/app/./routes/health.tsx");
  "health-it": typeof import("./public-app/app/./routes/health.tsx");
  "health-ja": typeof import("./public-app/app/./routes/health.tsx");
  "health-ko": typeof import("./public-app/app/./routes/health.tsx");
  "health-pt": typeof import("./public-app/app/./routes/health.tsx");
  "health-ro": typeof import("./public-app/app/./routes/health.tsx");
  "health-zh": typeof import("./public-app/app/./routes/health.tsx");
  "clinic-tr": typeof import("./public-app/app/./routes/clinic.tsx");
  "transfer-en": typeof import("./public-app/app/./routes/transfer.tsx");
  "transfer-localized": typeof import("./public-app/app/./routes/transfer.tsx");
  "hotel-de": typeof import("./public-app/app/./routes/hotel.tsx");
  "legal-imprint-en": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-privacy-en": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-privacy-de": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-imprint-de": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-privacy-tr": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-imprint-tr": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-privacy-ru": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-imprint-ru": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-privacy-cs": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-imprint-cs": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-privacy-uk": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-imprint-uk": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-privacy-ur": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-imprint-ur": typeof import("./public-app/app/./routes/legal.tsx");
  "blog-ru": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-de": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-en": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-pl": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-uk": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-nl": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-cs": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-ro": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-tr": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-he": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-fr": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-sv": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-da": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-ar": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-hu": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-es": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-it": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-pt": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-el": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-zh": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-ko": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-ja": typeof import("./public-app/app/./routes/blog.tsx");
  "blog-ur": typeof import("./public-app/app/./routes/blog.tsx");
  "article-ru": typeof import("./public-app/app/./routes/article.tsx");
  "article-de": typeof import("./public-app/app/./routes/article.tsx");
  "article-en": typeof import("./public-app/app/./routes/article.tsx");
  "article-pl": typeof import("./public-app/app/./routes/article.tsx");
  "article-uk": typeof import("./public-app/app/./routes/article.tsx");
  "article-nl": typeof import("./public-app/app/./routes/article.tsx");
  "article-cs": typeof import("./public-app/app/./routes/article.tsx");
  "article-ro": typeof import("./public-app/app/./routes/article.tsx");
  "article-tr": typeof import("./public-app/app/./routes/article.tsx");
  "article-he": typeof import("./public-app/app/./routes/article.tsx");
  "article-fr": typeof import("./public-app/app/./routes/article.tsx");
  "article-sv": typeof import("./public-app/app/./routes/article.tsx");
  "article-da": typeof import("./public-app/app/./routes/article.tsx");
  "article-ar": typeof import("./public-app/app/./routes/article.tsx");
  "article-hu": typeof import("./public-app/app/./routes/article.tsx");
  "article-es": typeof import("./public-app/app/./routes/article.tsx");
  "article-it": typeof import("./public-app/app/./routes/article.tsx");
  "article-pt": typeof import("./public-app/app/./routes/article.tsx");
  "article-el": typeof import("./public-app/app/./routes/article.tsx");
  "article-zh": typeof import("./public-app/app/./routes/article.tsx");
  "article-ko": typeof import("./public-app/app/./routes/article.tsx");
  "article-ja": typeof import("./public-app/app/./routes/article.tsx");
  "article-ur": typeof import("./public-app/app/./routes/article.tsx");
};