// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/de": {
    params: {};
  };
  "/tr": {
    params: {};
  };
  "/ru": {
    params: {};
  };
  "/cs": {
    params: {};
  };
  "/uk": {
    params: {};
  };
  "/ur": {
    params: {};
  };
  "/health": {
    params: {};
  };
  "/de/health": {
    params: {};
  };
  "/tr/health": {
    params: {};
  };
  "/ru/health": {
    params: {};
  };
  "/cs/health": {
    params: {};
  };
  "/uk/health": {
    params: {};
  };
  "/ur/health": {
    params: {};
  };
  "/clinic": {
    params: {};
  };
  "/transfers/:slug": {
    params: {
      "slug": string;
    };
  };
  "/:language/transfers/:slug": {
    params: {
      "language": string;
      "slug": string;
    };
  };
  "/impressum.html": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/de/datenschutz": {
    params: {};
  };
  "/de/impressum": {
    params: {};
  };
  "/tr/gizlilik": {
    params: {};
  };
  "/tr/kunye": {
    params: {};
  };
  "/ru/privacy": {
    params: {};
  };
  "/ru/impressum": {
    params: {};
  };
  "/cs/privacy": {
    params: {};
  };
  "/cs/impressum": {
    params: {};
  };
  "/uk/privacy": {
    params: {};
  };
  "/uk/impressum": {
    params: {};
  };
  "/ur/privacy": {
    params: {};
  };
  "/ur/impressum": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/de" | "/tr" | "/ru" | "/cs" | "/uk" | "/ur" | "/health" | "/de/health" | "/tr/health" | "/ru/health" | "/cs/health" | "/uk/health" | "/ur/health" | "/clinic" | "/transfers/:slug" | "/:language/transfers/:slug" | "/impressum.html" | "/privacy" | "/de/datenschutz" | "/de/impressum" | "/tr/gizlilik" | "/tr/kunye" | "/ru/privacy" | "/ru/impressum" | "/cs/privacy" | "/cs/impressum" | "/uk/privacy" | "/uk/impressum" | "/ur/privacy" | "/ur/impressum";
  };
  "./routes/home.tsx": {
    id: "home-en";
    page: "/";
  } | {
    id: "home-de";
    page: "/de";
  } | {
    id: "home-tr";
    page: "/tr";
  } | {
    id: "home-ru";
    page: "/ru";
  } | {
    id: "home-cs";
    page: "/cs";
  } | {
    id: "home-uk";
    page: "/uk";
  } | {
    id: "home-ur";
    page: "/ur";
  };
  "./routes/health.tsx": {
    id: "health-en";
    page: "/health";
  } | {
    id: "health-de";
    page: "/de/health";
  } | {
    id: "health-tr";
    page: "/tr/health";
  } | {
    id: "health-ru";
    page: "/ru/health";
  } | {
    id: "health-cs";
    page: "/cs/health";
  } | {
    id: "health-uk";
    page: "/uk/health";
  } | {
    id: "health-ur";
    page: "/ur/health";
  };
  "./routes/clinic.tsx": {
    id: "clinic-tr";
    page: "/clinic";
  };
  "./routes/transfer.tsx": {
    id: "transfer-en";
    page: "/transfers/:slug";
  } | {
    id: "transfer-localized";
    page: "/:language/transfers/:slug";
  };
  "./routes/legal.tsx": {
    id: "legal-imprint-en";
    page: "/impressum.html";
  } | {
    id: "legal-privacy-en";
    page: "/privacy";
  } | {
    id: "legal-privacy-de";
    page: "/de/datenschutz";
  } | {
    id: "legal-imprint-de";
    page: "/de/impressum";
  } | {
    id: "legal-privacy-tr";
    page: "/tr/gizlilik";
  } | {
    id: "legal-imprint-tr";
    page: "/tr/kunye";
  } | {
    id: "legal-privacy-ru";
    page: "/ru/privacy";
  } | {
    id: "legal-imprint-ru";
    page: "/ru/impressum";
  } | {
    id: "legal-privacy-cs";
    page: "/cs/privacy";
  } | {
    id: "legal-imprint-cs";
    page: "/cs/impressum";
  } | {
    id: "legal-privacy-uk";
    page: "/uk/privacy";
  } | {
    id: "legal-imprint-uk";
    page: "/uk/impressum";
  } | {
    id: "legal-privacy-ur";
    page: "/ur/privacy";
  } | {
    id: "legal-imprint-ur";
    page: "/ur/impressum";
  };
};

type RouteModules = {
  "root": typeof import("./public-app/app/root.tsx");
  "home-en": typeof import("./public-app/app/./routes/home.tsx");
  "home-de": typeof import("./public-app/app/./routes/home.tsx");
  "home-tr": typeof import("./public-app/app/./routes/home.tsx");
  "home-ru": typeof import("./public-app/app/./routes/home.tsx");
  "home-cs": typeof import("./public-app/app/./routes/home.tsx");
  "home-uk": typeof import("./public-app/app/./routes/home.tsx");
  "home-ur": typeof import("./public-app/app/./routes/home.tsx");
  "health-en": typeof import("./public-app/app/./routes/health.tsx");
  "health-de": typeof import("./public-app/app/./routes/health.tsx");
  "health-tr": typeof import("./public-app/app/./routes/health.tsx");
  "health-ru": typeof import("./public-app/app/./routes/health.tsx");
  "health-cs": typeof import("./public-app/app/./routes/health.tsx");
  "health-uk": typeof import("./public-app/app/./routes/health.tsx");
  "health-ur": typeof import("./public-app/app/./routes/health.tsx");
  "clinic-tr": typeof import("./public-app/app/./routes/clinic.tsx");
  "transfer-en": typeof import("./public-app/app/./routes/transfer.tsx");
  "transfer-localized": typeof import("./public-app/app/./routes/transfer.tsx");
  "legal-imprint-en": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-privacy-en": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-privacy-de": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-imprint-de": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-privacy-tr": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-imprint-tr": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-privacy-ru": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-imprint-ru": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-privacy-cs": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-imprint-cs": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-privacy-uk": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-imprint-uk": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-privacy-ur": typeof import("./public-app/app/./routes/legal.tsx");
  "legal-imprint-ur": typeof import("./public-app/app/./routes/legal.tsx");
};