import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("./routes/home.tsx", { id: "home-en" }),
  route("de", "./routes/home.tsx", { id: "home-de" }),
  route("fr", "./routes/home.tsx", { id: "home-fr" }),
  route("tr", "./routes/home.tsx", { id: "home-tr" }),
  route("ru", "./routes/home.tsx", { id: "home-ru" }),
  route("cs", "./routes/home.tsx", { id: "home-cs" }),
  route("uk", "./routes/home.tsx", { id: "home-uk" }),
  route("ur", "./routes/home.tsx", { id: "home-ur" }),
  route("pl", "./routes/home.tsx", { id: "home-pl" }),
  route("nl", "./routes/home.tsx", { id: "home-nl" }),
  route("ar", "./routes/home.tsx", { id: "home-ar" }),
  route("sv", "./routes/home.tsx", { id: "home-sv" }),
  route("health", "./routes/health.tsx", { id: "health-en" }),
  route("de/health", "./routes/health.tsx", { id: "health-de" }),
  route("fr/health", "./routes/health.tsx", { id: "health-fr" }),
  route("tr/health", "./routes/health.tsx", { id: "health-tr" }),
  route("ru/health", "./routes/health.tsx", { id: "health-ru" }),
  route("cs/health", "./routes/health.tsx", { id: "health-cs" }),
  route("uk/health", "./routes/health.tsx", { id: "health-uk" }),
  route("ur/health", "./routes/health.tsx", { id: "health-ur" }),
  route("pl/health", "./routes/health.tsx", { id: "health-pl" }),
  route("nl/health", "./routes/health.tsx", { id: "health-nl" }),
  route("ar/health", "./routes/health.tsx", { id: "health-ar" }),
  route("sv/health", "./routes/health.tsx", { id: "health-sv" }),
  route("clinic", "./routes/clinic.tsx", { id: "clinic-tr" }),
route("transfers/:slug", "./routes/transfer.tsx", { id: "transfer-en" }),
  route(":language/transfers/:slug", "./routes/transfer.tsx", { id: "transfer-localized" }),
  route("de/hotels/:hotelSlug", "./routes/hotel.tsx", { id: "hotel-de" }),
  route("impressum.html", "./routes/legal.tsx", { id: "legal-imprint-en" }),
  route("privacy", "./routes/legal.tsx", { id: "legal-privacy-en" }),
  route("de/datenschutz", "./routes/legal.tsx", { id: "legal-privacy-de" }),
  route("de/impressum", "./routes/legal.tsx", { id: "legal-imprint-de" }),
  route("tr/gizlilik", "./routes/legal.tsx", { id: "legal-privacy-tr" }),
  route("tr/kunye", "./routes/legal.tsx", { id: "legal-imprint-tr" }),
  route("ru/privacy", "./routes/legal.tsx", { id: "legal-privacy-ru" }),
  route("ru/impressum", "./routes/legal.tsx", { id: "legal-imprint-ru" }),
  route("cs/privacy", "./routes/legal.tsx", { id: "legal-privacy-cs" }),
  route("cs/impressum", "./routes/legal.tsx", { id: "legal-imprint-cs" }),
  route("uk/privacy", "./routes/legal.tsx", { id: "legal-privacy-uk" }),
  route("uk/impressum", "./routes/legal.tsx", { id: "legal-imprint-uk" }),
  route("ur/privacy", "./routes/legal.tsx", { id: "legal-privacy-ur" }),
  route("ur/impressum", "./routes/legal.tsx", { id: "legal-imprint-ur" }),
] satisfies RouteConfig;
